//
// Autogenerated by Thrift Compiler (0.22.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import thrift = require('thrift');
import Thrift = thrift.Thrift;
import Q = thrift.Q;
import Int64 = require('node-int64');


/**
 * Minimum length of any string-based attribute, in Unicode chars
 */
declare var EDAM_ATTRIBUTE_LEN_MIN: number;

/**
 * Maximum length of any string-based attribute, in Unicode chars
 */
declare var EDAM_ATTRIBUTE_LEN_MAX: number;

/**
 * Any string-based attribute must match the provided regular expression.
 * This excludes all Unicode line endings and control characters.
 */
declare var EDAM_ATTRIBUTE_REGEX: string;

/**
 * The maximum number of values that can be stored in a list-based attribute
 * (e.g. see UserAttributes.recentMailedAddresses)
 */
declare var EDAM_ATTRIBUTE_LIST_MAX: number;

/**
 * The maximum number of entries that can be stored in a map-based attribute
 * such as applicationData fields in Resources and Notes.
 */
declare var EDAM_ATTRIBUTE_MAP_MAX: number;

/**
 * The minimum length of a GUID generated by the Evernote service
 */
declare var EDAM_GUID_LEN_MIN: number;

/**
 * The maximum length of a GUID generated by the Evernote service
 */
declare var EDAM_GUID_LEN_MAX: number;

/**
 * GUIDs generated by the Evernote service will match the provided pattern
 */
declare var EDAM_GUID_REGEX: string;

/**
 * The minimum length of any email address
 */
declare var EDAM_EMAIL_LEN_MIN: number;

/**
 * The maximum length of any email address
 */
declare var EDAM_EMAIL_LEN_MAX: number;

/**
 * A regular expression that matches the part of an email address before
 * the '@' symbol.
 */
declare var EDAM_EMAIL_LOCAL_REGEX: string;

/**
 * A regular expression that matches the part of an email address after
 * the '@' symbol.
 */
declare var EDAM_EMAIL_DOMAIN_REGEX: string;

/**
 * A regular expression that must match any email address given to Evernote.
 * Email addresses must comply with RFC 2821 and 2822.
 */
declare var EDAM_EMAIL_REGEX: string;

/**
 * A regular expression that must match any VAT ID given to Evernote.
 * ref http://en.wikipedia.org/wiki/VAT_identification_number
 * ref http://my.safaribooksonline.com/book/programming/regular-expressions/9780596802837/4dot-validation-and-formatting/id2995136
 */
declare var EDAM_VAT_REGEX: string;

/**
 * The minimum length of a timezone specification string
 */
declare var EDAM_TIMEZONE_LEN_MIN: number;

/**
 * The maximum length of a timezone specification string
 */
declare var EDAM_TIMEZONE_LEN_MAX: number;

/**
 * Any timezone string given to Evernote must match the provided pattern.
 * This permits either a locale-based standard timezone or a GMT offset.
 * E.g.:<ul>
 *    <li>America/Los_Angeles</li>
 *    <li>GMT+08:00</li>
 * </ul>
 */
declare var EDAM_TIMEZONE_REGEX: string;

/**
 * The minimum length of any MIME type string given to Evernote
 */
declare var EDAM_MIME_LEN_MIN: number;

/**
 * The maximum length of any MIME type string given to Evernote
 */
declare var EDAM_MIME_LEN_MAX: number;

/**
 * Any MIME type string given to Evernote must match the provided pattern.
 * E.g.:  image/gif
 */
declare var EDAM_MIME_REGEX: string;

/**
 * Canonical MIME type string for GIF image resources
 */
declare var EDAM_MIME_TYPE_GIF: string;

/**
 * Canonical MIME type string for JPEG image resources
 */
declare var EDAM_MIME_TYPE_JPEG: string;

/**
 * Canonical MIME type string for PNG image resources
 */
declare var EDAM_MIME_TYPE_PNG: string;

/**
 * Canonical MIME type string for TIFF image resources
 */
declare var EDAM_MIME_TYPE_TIFF: string;

/**
 * Canonical MIME type string for BMP image resources
 */
declare var EDAM_MIME_TYPE_BMP: string;

/**
 * Canonical MIME type string for WAV audio resources
 */
declare var EDAM_MIME_TYPE_WAV: string;

/**
 * Canonical MIME type string for MP3 audio resources
 */
declare var EDAM_MIME_TYPE_MP3: string;

/**
 * Canonical MIME type string for AMR audio resources
 */
declare var EDAM_MIME_TYPE_AMR: string;

/**
 * Canonical MIME type string for AAC audio resources
 */
declare var EDAM_MIME_TYPE_AAC: string;

/**
 * Canonical MIME type string for MP4 audio resources
 */
declare var EDAM_MIME_TYPE_M4A: string;

/**
 * Canonical MIME type string for MP4 video resources
 */
declare var EDAM_MIME_TYPE_MP4_VIDEO: string;

/**
 * Canonical MIME type string for Evernote Ink resources
 */
declare var EDAM_MIME_TYPE_INK: string;

/**
 * Canonical MIME type string for PDF resources
 */
declare var EDAM_MIME_TYPE_PDF: string;

/**
 * MIME type used for attachments of an unspecified type
 */
declare var EDAM_MIME_TYPE_DEFAULT: string;

/**
 * The set of resource MIME types that are expected to be handled
 * correctly by all of the major Evernote client applications.
 */
declare var EDAM_MIME_TYPES: string[];

/**
 * The set of MIME types that Evernote will parse and index for
 * searching. With exception of images, PDFs and plain text files,
 * which are handled in a different way.
 */
declare var EDAM_INDEXABLE_RESOURCE_MIME_TYPES: string[];

/**
 * The set of plain text MIME types that Evernote will parse and index
 * for searching. The MIME types which start with "text/" will be handled
 * separately by each client (i.e. hard-coded in each client).
 */
declare var EDAM_INDEXABLE_PLAINTEXT_MIME_TYPES: string[];

/**
 * The minimum length of a user search query string in Unicode chars
 */
declare var EDAM_SEARCH_QUERY_LEN_MIN: number;

/**
 * The maximum length of a user search query string in Unicode chars
 */
declare var EDAM_SEARCH_QUERY_LEN_MAX: number;

/**
 * Search queries must match the provided pattern.  This is used for
 * both ad-hoc queries and SavedSearch.query fields.
 * This excludes all control characters and line/paragraph separators.
 */
declare var EDAM_SEARCH_QUERY_REGEX: string;

/**
 * The exact length of a MD5 hash checksum, in binary bytes.
 * This is the exact length that must be matched for any binary hash
 * value.
 */
declare var EDAM_HASH_LEN: number;

/**
 * The minimum length of an Evernote username
 */
declare var EDAM_USER_USERNAME_LEN_MIN: number;

/**
 * The maximum length of an Evernote username
 */
declare var EDAM_USER_USERNAME_LEN_MAX: number;

/**
 * Any Evernote User.username field must match this pattern.  This
 * restricts usernames to a format that could permit use as a domain
 * name component.  E.g. "username.whatever.evernote.com"
 */
declare var EDAM_USER_USERNAME_REGEX: string;

/**
 * Minimum length of the User.name field
 */
declare var EDAM_USER_NAME_LEN_MIN: number;

/**
 * Maximum length of the User.name field
 */
declare var EDAM_USER_NAME_LEN_MAX: number;

/**
 * The User.name field must match this pattern, which excludes line
 * endings and control characters.
 */
declare var EDAM_USER_NAME_REGEX: string;

/**
 * The minimum length of a Tag.name, in Unicode characters
 */
declare var EDAM_TAG_NAME_LEN_MIN: number;

/**
 * The maximum length of a Tag.name, in Unicode characters
 */
declare var EDAM_TAG_NAME_LEN_MAX: number;

/**
 * All Tag.name fields must match this pattern.
 * This excludes control chars, commas or line/paragraph separators.
 * The string may not begin or end with whitespace.
 */
declare var EDAM_TAG_NAME_REGEX: string;

/**
 * The minimum length of a Note.title, in Unicode characters
 */
declare var EDAM_NOTE_TITLE_LEN_MIN: number;

/**
 * The maximum length of a Note.title, in Unicode characters
 */
declare var EDAM_NOTE_TITLE_LEN_MAX: number;

/**
 * All Note.title fields must match this pattern.
 * This excludes control chars or line/paragraph separators.
 * The string may not begin or end with whitespace.
 */
declare var EDAM_NOTE_TITLE_REGEX: string;

/**
 * Minimum length of a Note.content field.
 * Note.content fields must comply with the ENML DTD.
 */
declare var EDAM_NOTE_CONTENT_LEN_MIN: number;

/**
 * Maximum length of a Note.content field
 * Note.content fields must comply with the ENML DTD.
 */
declare var EDAM_NOTE_CONTENT_LEN_MAX: number;

/**
 * Minimum length of an application name, which is the key in an
 * applicationData LazyMap found in entities such as Resources and
 * Notes.
 */
declare var EDAM_APPLICATIONDATA_NAME_LEN_MIN: number;

/**
 * Maximum length of an application name, which is the key in an
 * applicationData LazyMap found in entities such as Resources and
 * Notes.
 */
declare var EDAM_APPLICATIONDATA_NAME_LEN_MAX: number;

/**
 * Minimum length of an applicationData value in a LazyMap, found
 * in entities such as Resources and Notes.
 */
declare var EDAM_APPLICATIONDATA_VALUE_LEN_MIN: number;

/**
 * Maximum length of an applicationData value in a LazyMap, found
 * in entities such as Resources and Notes.  Note, however, that
 * the sum of the size of hte key and value is constrained by
 * EDAM_APPLICATIONDATA_ENTRY_LEN_MAX, so the maximum length, in
 * practice, depends upon the key value being used.
 */
declare var EDAM_APPLICATIONDATA_VALUE_LEN_MAX: number;

/**
 * The total length of an entry in an applicationData LazyMap, which
 * is the sum of the length of the key and the value for the entry.
 */
declare var EDAM_APPLICATIONDATA_ENTRY_LEN_MAX: number;

/**
 * An application name must match this regex.  An application
 * name is the key portion of an entry in an applicationData
 * map as found in entities such as Resources and Notes.
 * Note that even if both the name and value regexes match,
 * it is still necessary to check the sum of the lengths
 * against EDAM_APPLICATIONDATA_ENTRY_LEN_MAX.
 */
declare var EDAM_APPLICATIONDATA_NAME_REGEX: string;

/**
 * An applicationData map value must match this regex.
 * Note that even if both the name and value regexes match,
 * it is still necessary to check the sum of the lengths
 * against EDAM_APPLICATIONDATA_ENTRY_LEN_MAX.
 */
declare var EDAM_APPLICATIONDATA_VALUE_REGEX: string;

/**
 * The minimum length of a Notebook.name, in Unicode characters
 */
declare var EDAM_NOTEBOOK_NAME_LEN_MIN: number;

/**
 * The maximum length of a Notebook.name, in Unicode characters
 */
declare var EDAM_NOTEBOOK_NAME_LEN_MAX: number;

/**
 * All Notebook.name fields must match this pattern.
 * This excludes control chars or line/paragraph separators.
 * The string may not begin or end with whitespace.
 */
declare var EDAM_NOTEBOOK_NAME_REGEX: string;

/**
 * The minimum length of a Notebook.stack, in Unicode characters
 */
declare var EDAM_NOTEBOOK_STACK_LEN_MIN: number;

/**
 * The maximum length of a Notebook.stack, in Unicode characters
 */
declare var EDAM_NOTEBOOK_STACK_LEN_MAX: number;

/**
 * All Notebook.stack fields must match this pattern.
 * This excludes control chars or line/paragraph separators.
 * The string may not begin or end with whitespace.
 */
declare var EDAM_NOTEBOOK_STACK_REGEX: string;

/**
 * The minimum length of a Workspace.name, in Unicode characters
 */
declare var EDAM_WORKSPACE_NAME_LEN_MIN: number;

/**
 * The maximum length of a Workspace.name, in Unicode characters
 */
declare var EDAM_WORKSPACE_NAME_LEN_MAX: number;

/**
 * The maximum length of a Workspace.description, in Unicode characters
 */
declare var EDAM_WORKSPACE_DESCRIPTION_LEN_MAX: number;

/**
 * All Workspace.name fields must match this pattern.
 * This excludes control chars or line/paragraph separators.
 * The string may not begin or end with whitespace.
 */
declare var EDAM_WORKSPACE_NAME_REGEX: string;

/**
 * The minimum length of a public notebook URI component
 */
declare var EDAM_PUBLISHING_URI_LEN_MIN: number;

/**
 * The maximum length of a public notebook URI component
 */
declare var EDAM_PUBLISHING_URI_LEN_MAX: number;

/**
 * A public notebook URI component must match the provided pattern
 */
declare var EDAM_PUBLISHING_URI_REGEX: string;

/**
 * The set of strings that may not be used as a publishing URI
 */
declare var EDAM_PUBLISHING_URI_PROHIBITED: string[];

/**
 * The minimum length of a Publishing.publicDescription field.
 */
declare var EDAM_PUBLISHING_DESCRIPTION_LEN_MIN: number;

/**
 * The maximum length of a Publishing.publicDescription field.
 */
declare var EDAM_PUBLISHING_DESCRIPTION_LEN_MAX: number;

/**
 * Any public notebook's Publishing.publicDescription field must match
 * this pattern.
 * No control chars or line/paragraph separators, and can't start or
 * end with whitespace.
 */
declare var EDAM_PUBLISHING_DESCRIPTION_REGEX: string;

/**
 * The minimum length of a SavedSearch.name field
 */
declare var EDAM_SAVED_SEARCH_NAME_LEN_MIN: number;

/**
 * The maximum length of a SavedSearch.name field
 */
declare var EDAM_SAVED_SEARCH_NAME_LEN_MAX: number;

/**
 * SavedSearch.name fields must match this pattern.
 * No control chars or line/paragraph separators, and can't start or
 * end with whitespace.
 */
declare var EDAM_SAVED_SEARCH_NAME_REGEX: string;

/**
 * The minimum length of an Evernote user password
 */
declare var EDAM_USER_PASSWORD_LEN_MIN: number;

/**
 * The maximum length of an Evernote user password
 */
declare var EDAM_USER_PASSWORD_LEN_MAX: number;

/**
 * Evernote user passwords must match this regular expression
 */
declare var EDAM_USER_PASSWORD_REGEX: string;

/**
 * The maximum length of an Evernote Business URI
 */
declare var EDAM_BUSINESS_URI_LEN_MAX: number;

/**
 * Valid Evernote Business marketing code / affiliate code format.
 */
declare var EDAM_BUSINESS_MARKETING_CODE_REGEX_PATTERN: string;

/**
 * The maximum number of Tags per Note
 */
declare var EDAM_NOTE_TAGS_MAX: number;

/**
 * The maximum number of Resources per Note
 */
declare var EDAM_NOTE_RESOURCES_MAX: number;

/**
 * Maximum number of Tags per account
 */
declare var EDAM_USER_TAGS_MAX: number;

/**
 * Maximum number of Tags per business account.
 */
declare var EDAM_BUSINESS_TAGS_MAX: number;

/**
 * Maximum number of SavedSearches per account
 */
declare var EDAM_USER_SAVED_SEARCHES_MAX: number;

/**
 * Maximum number of Notes per user
 */
declare var EDAM_USER_NOTES_MAX: number;

/**
 * Maximum number of Notes per business account
 */
declare var EDAM_BUSINESS_NOTES_MAX: number;

/**
 * Maximum number of Notebooks per user
 */
declare var EDAM_USER_NOTEBOOKS_MAX: number;

/**
 * Maximum number of Workspaces per user
 */
declare var EDAM_USER_WORKSPACES_MAX: number;

/**
 * Maximum number of Notebooks in a business account
 */
declare var EDAM_BUSINESS_NOTEBOOKS_MAX: number;

/**
 * Maximum number of Workspaces in a business account
 */
declare var EDAM_BUSINESS_WORKSPACES_MAX: number;

/**
 * Maximum number of recent email addresses that are maintained
 * (see UserAttributes.recentMailedAddresses)
 */
declare var EDAM_USER_RECENT_MAILED_ADDRESSES_MAX: number;

/**
 * The number of emails of any type that can be sent by a user with a Free
 * account from the service per day.  If an email is sent to two different
 * recipients, this counts as two emails.
 */
declare var EDAM_USER_MAIL_LIMIT_DAILY_FREE: number;

/**
 * The number of emails of any type that can be sent by a user with a Premium
 * account from the service per day.  If an email is sent to two different
 * recipients, this counts as two emails.
 */
declare var EDAM_USER_MAIL_LIMIT_DAILY_PREMIUM: number;

/**
 * The number of bytes of new data that may be uploaded to a Free user's
 * account each month.
 */
declare var EDAM_USER_UPLOAD_LIMIT_FREE: Int64;

/**
 * The number of bytes of new data that may be uploaded to a Premium user's
 * account each month.
 */
declare var EDAM_USER_UPLOAD_LIMIT_PREMIUM: Int64;

/**
 * The number of bytes of new data that may be uploaded to new business
 * account during the first month. 50GB.
 */
declare var EDAM_USER_UPLOAD_LIMIT_BUSINESS_FIRST_MONTH: Int64;

/**
 * The number of bytes of new data that may be uploaded to a business
 * account for the next month. 20GB.
 */
declare var EDAM_USER_UPLOAD_LIMIT_BUSINESS_NEXT_MONTH: Int64;

/**
 * The number of bytes of new data that may be uploaded each month to an account at
 * a Plus service level.
 */
declare var EDAM_USER_UPLOAD_LIMIT_PLUS: Int64;

/**
 * The number of bytes of new data uploaded in a monthly quota cycle at which point
 * users should be prompted with a survey to gather information on how they are using
 * Evernote.
 */
declare var EDAM_USER_UPLOAD_SURVEY_THRESHOLD: Int64;

/**
 * The number of bytes of new data that may be uploaded to a Business user's
 * personal account each month. Note that content uploaded into the Business
 * notebooks by the user does not count against this limit.
 */
declare var EDAM_USER_UPLOAD_LIMIT_BUSINESS: Int64;

/**
 * The number of bytes of new data that may be uploaded to a Business for each
 * member of the business per month. The total bytes available can be determined
 * by multiplying this with the number of business users.
 */
declare var EDAM_USER_UPLOAD_LIMIT_BUSINESS_PER_USER: Int64;

/**
 * Maximum total size of a Note that can be added to a Free account.
 * The size of a note is calculated as:
 * ENML content length (in Unicode characters) plus the sum of all resource
 * sizes (in bytes).
 */
declare var EDAM_NOTE_SIZE_MAX_FREE: number;

/**
 * Maximum total size of a Note that can be added to a Premium account.
 * The size of a note is calculated as:
 * ENML content length (in Unicode characters) plus the sum of all resource
 * sizes (in bytes).
 */
declare var EDAM_NOTE_SIZE_MAX_PREMIUM: number;

/**
 * Maximum size of a resource, in bytes, for Free accounts
 */
declare var EDAM_RESOURCE_SIZE_MAX_FREE: number;

/**
 * Maximum size of a resource, in bytes, for Premium accounts
 */
declare var EDAM_RESOURCE_SIZE_MAX_PREMIUM: number;

/**
 * Maximum number of linked notebooks per account, for a free
 * account.
 */
declare var EDAM_USER_LINKED_NOTEBOOK_MAX: number;

/**
 * Maximum number of linked notebooks per account, for a premium
 * account.  Users who are part of an active business are also
 * covered under "premium".
 */
declare var EDAM_USER_LINKED_NOTEBOOK_MAX_PREMIUM: number;

/**
 * Maximum number of shared notebooks per business notebook
 */
declare var EDAM_NOTEBOOK_BUSINESS_SHARED_NOTEBOOK_MAX: number;

/**
 * Maximum number of shared notebooks per personal notebook
 */
declare var EDAM_NOTEBOOK_PERSONAL_SHARED_NOTEBOOK_MAX: number;

/**
 * Maximum number of SharedNote records per business note
 */
declare var EDAM_NOTE_BUSINESS_SHARED_NOTE_MAX: number;

/**
 * Maximum number of SharedNote records per personal note
 */
declare var EDAM_NOTE_PERSONAL_SHARED_NOTE_MAX: number;

/**
 * The minimum length of the content class attribute of a note.
 */
declare var EDAM_NOTE_CONTENT_CLASS_LEN_MIN: number;

/**
 * The maximum length of the content class attribute of a note.
 */
declare var EDAM_NOTE_CONTENT_CLASS_LEN_MAX: number;

/**
 * The regular expression that the content class of a note must match
 * to be valid.
 */
declare var EDAM_NOTE_CONTENT_CLASS_REGEX: string;

/**
 * The content class prefix used for all notes created by Evernote Hello.
 * This prefix can be used to assemble individual content class strings,
 * or can be used to create a wildcard search to get all notes created by
 * Hello. When performing a wildcard search via filtered sync chunks or
 * search strings, the * character must be appended to this constant.
 */
declare var EDAM_HELLO_APP_CONTENT_CLASS_PREFIX: string;

/**
 * The content class prefix used for all notes created by Evernote Food.
 * This prefix can be used to assemble individual content class strings,
 * or can be used to create a wildcard search to get all notes created by
 * Food. When performing a wildcard search via filtered sync chunks or
 * search strings, the * character must be appended to this constant.
 */
declare var EDAM_FOOD_APP_CONTENT_CLASS_PREFIX: string;

/**
 * The content class prefix used for structured notes created by Evernote
 * Hello that represents an encounter with a person. When performing a
 * wildcard search via filtered sync chunks or search strings, the *
 * character must be appended to this constant.
 */
declare var EDAM_CONTENT_CLASS_HELLO_ENCOUNTER: string;

/**
 * The content class prefix used for structured notes created by Evernote
 * Hello that represents the user's profile. When performing a
 * wildcard search via filtered sync chunks or search strings, the *
 * character must be appended to this constant.
 */
declare var EDAM_CONTENT_CLASS_HELLO_PROFILE: string;

/**
 * The content class prefix used for structured notes created by
 * Evernote Food that captures the experience of a particular meal.
 * When performing a wildcard search via filtered sync chunks or search
 * strings, the * character must be appended to this constant.
 */
declare var EDAM_CONTENT_CLASS_FOOD_MEAL: string;

/**
 * The content class prefix used for structured notes created by Evernote
 * Skitch. When performing a wildcard search via filtered sync chunks
 * or search strings, the * character must be appended to this constant.
 */
declare var EDAM_CONTENT_CLASS_SKITCH_PREFIX: string;

/**
 * The content class value used for structured image notes created by Evernote
 * Skitch.
 */
declare var EDAM_CONTENT_CLASS_SKITCH: string;

/**
 * The content class value used for structured PDF notes created by Evernote
 * Skitch.
 */
declare var EDAM_CONTENT_CLASS_SKITCH_PDF: string;

/**
 * The content class prefix used for structured notes created by Evernote
 * Penultimate. When performing a wildcard search via filtered sync chunks
 * or search strings, the * character must be appended to this constant.
 */
declare var EDAM_CONTENT_CLASS_PENULTIMATE_PREFIX: string;

/**
 * The content class value used for structured notes created by Evernote
 * Penultimate that represents a Penultimate notebook.
 */
declare var EDAM_CONTENT_CLASS_PENULTIMATE_NOTEBOOK: string;

/**
 * The NoteAttributes.sourceApplication value used for notes captured by the Post-it
 * camera.
 */
declare var EDAM_SOURCE_APPLICATION_POSTIT: string;

/**
 * The NoteAttributes.sourceApplication value used for notes captured by the Moleskine
 * page camera.
 */
declare var EDAM_SOURCE_APPLICATION_MOLESKINE: string;

/**
 * The NoteAttributes.sourceApplication value used for notes captured by
 * PFU ScanSnap Evernote Edition.
 */
declare var EDAM_SOURCE_APPLICATION_EN_SCANSNAP: string;

/**
 * The NoteAttributes.sourceApplication value used for notes captured with the Embedded
 * Web Clipper.
 */
declare var EDAM_SOURCE_APPLICATION_EWC: string;

/**
 * The NoteAttributes.sourceApplication value used for notes captured with the Android
 * share extension.
 */
declare var EDAM_SOURCE_APPLICATION_ANDROID_SHARE_EXTENSION: string;

/**
 * The NoteAttributes.sourceApplication value used for notes captured with the iOS share
 * extension.
 */
declare var EDAM_SOURCE_APPLICATION_IOS_SHARE_EXTENSION: string;

/**
 * The NoteAttributes.sourceApplication value used for notes captured with the Evernote
 * Web Clipper.
 */
declare var EDAM_SOURCE_APPLICATION_WEB_CLIPPER: string;

/**
 * The NoteAttributes.source value used for notes captured by the Microsoft Outlook clipper.
 */
declare var EDAM_SOURCE_OUTLOOK_CLIPPER: string;

/**
 * A NoteAttributes.noteTitleQuality value indicating that a note has no meaningful title,
 * only a placeholder value such as "Untitled Note".
 */
declare var EDAM_NOTE_TITLE_QUALITY_UNTITLED: number;

/**
 * A NoteAttributes.noteTitleQuality value indicating that the quality of an automatically
 * generated note title is low. Examples of low quality titles include those based on a
 * note's type and location, such as "Snapshot from 123 Sesame Street in New York".
 */
declare var EDAM_NOTE_TITLE_QUALITY_LOW: number;

/**
 * A NoteAttributes.noteTitleQuality value indicating that the quality of an automatically
 * generated note title is medium. Examples of medium quality titles include those based on a
 * calendar entry, such as "Note from Weekly Staff Meeting".
 */
declare var EDAM_NOTE_TITLE_QUALITY_MEDIUM: number;

/**
 * A NoteAttributes.noteTitleQuality value indicating that the quality of an automatically
 * generated note title is high. Examples of high quality titles include those based on a
 * scanned business card, such as "John Doe - Scanned Business Card".
 */
declare var EDAM_NOTE_TITLE_QUALITY_HIGH: number;

/**
 * The minimum length of the plain text in a findRelated query, assuming that
 * plaintext is being provided.
 */
declare var EDAM_RELATED_PLAINTEXT_LEN_MIN: number;

/**
 * The maximum length of the plain text in a findRelated query, assuming that
 * plaintext is being provided.
 */
declare var EDAM_RELATED_PLAINTEXT_LEN_MAX: number;

/**
 * The maximum number of notes that will be returned from a findRelated()
 * query.
 */
declare var EDAM_RELATED_MAX_NOTES: number;

/**
 * The maximum number of notebooks that will be returned from a findRelated()
 * query.
 */
declare var EDAM_RELATED_MAX_NOTEBOOKS: number;

/**
 * The maximum number of tags that will be returned from a findRelated() query.
 */
declare var EDAM_RELATED_MAX_TAGS: number;

/**
 * The maximum number of experts that will be returned from a findRelated() query
 */
declare var EDAM_RELATED_MAX_EXPERTS: number;

/**
 * The maximum number of related content snippets that will be returned from a
 * findRelated() query.
 */
declare var EDAM_RELATED_MAX_RELATED_CONTENT: number;

/**
 * The minimum length, in Unicode characters, of a description for a business
 * notebook.
 */
declare var EDAM_BUSINESS_NOTEBOOK_DESCRIPTION_LEN_MIN: number;

/**
 * The maximum length, in Unicode characters, of a description for a business
 * notebook.
 */
declare var EDAM_BUSINESS_NOTEBOOK_DESCRIPTION_LEN_MAX: number;

/**
 * All business notebook descriptions must match this pattern.
 * This excludes control chars or line/paragraph separators.
 * The string may not begin or end with whitespace.
 */
declare var EDAM_BUSINESS_NOTEBOOK_DESCRIPTION_REGEX: string;

/**
 * The maximum length of a business phone number.
 */
declare var EDAM_BUSINESS_PHONE_NUMBER_LEN_MAX: number;

/**
 * Minimum length of a preference name
 */
declare var EDAM_PREFERENCE_NAME_LEN_MIN: number;

/**
 * Maximum length of a preference name
 */
declare var EDAM_PREFERENCE_NAME_LEN_MAX: number;

/**
 * Minimum length of a preference value
 */
declare var EDAM_PREFERENCE_VALUE_LEN_MIN: number;

/**
 * Maximum length of a preference value
 */
declare var EDAM_PREFERENCE_VALUE_LEN_MAX: number;

/**
 * Maximum number of name/value pairs allowed
 */
declare var EDAM_MAX_PREFERENCES: number;

/**
 * Maximum number of values per preference name when using
 * values of size no greater than EDAM_PREFERENCE_VALUE_LEN_MAX.
 */
declare var EDAM_MAX_VALUES_PER_PREFERENCE: number;

/**
 * The maximum length of a preference value if you only use one value
 * per preference rather than up to EDAM_MAX_VALUES_PER_PREFERENCE.
 * This option is useful if you want a single string that is larger
 * than EDAM_PREFERENCE_VALUE_LEN_MAX and would otherwise need to
 * split the string into multiple pieces to store it.
 */
declare var EDAM_PREFERENCE_ONLY_ONE_VALUE_LEN_MAX: number;

/**
 * A preference name must match this regex.
 */
declare var EDAM_PREFERENCE_NAME_REGEX: string;

/**
 * A preference value must match this regex if you are using more
 * than a single value for a preference.
 */
declare var EDAM_PREFERENCE_VALUE_REGEX: string;

/**
 * A preference value must match this regex if you are using a single
 * value for a preference.
 */
declare var EDAM_PREFERENCE_ONLY_ONE_VALUE_REGEX: string;

/**
 * The name of the preferences entry that contains shortcuts.
 */
declare var EDAM_PREFERENCE_SHORTCUTS: string;

/**
 * The name of the preferences entry that contains the notebook GUID (not the linked notebook) of
 * the default business notebook. It must be in the format EDAM_GUID_REGEX.
 * If a default business notebook is not set and the user is a business user
 * the user should be prompted to set the default business notebook.
 * The default business notebook must be a read/write notebook.
 * Whenever the default business notebook guid is used, it must be revalidiated as a writable
 * notebook. If it is not valid, the user should be re-prompted to set the value.
 * This value is used by clients only.
 */
declare var EDAM_PREFERENCE_BUSINESS_DEFAULT_NOTEBOOK: string;

/**
 * The name of the preferences entry that contains a boolean indicating that default
 * quicknotes should go into a business notebook. The EDAM_PREFERENCE_BUSINESS_DEFAULT_NOTEBOOK
 * must be set correctly for this preference to be honored.
 * The quicknote preferences should only be set to "true", if quicknote should use a business
 * notebook.
 * Any value other than "true" (or the omission of a value) should be treated as "false".
 * In this case, quicknotes should be created in in the user's personal default notebook.
 * The interface should not allow users to set quicknote to a business notebook
 * without a valid default business notebook selected, however, clients should handle the edge
 * case of an invalid business notebook guid.  If a user stops being a business user or
 * does not have write access to any business notebooks the quicknote preference should be
 * ignored.
 */
declare var EDAM_PREFERENCE_BUSINESS_QUICKNOTE: string;

/**
 * The maximum number of shortcuts that a user may have.
 */
declare var EDAM_PREFERENCE_SHORTCUTS_MAX_VALUES: number;

/**
 * Maximum length of the device identifier string associated with long sessions.
 */
declare var EDAM_DEVICE_ID_LEN_MAX: number;

/**
 * Regular expression for device identifier strings associated with long sessions.
 */
declare var EDAM_DEVICE_ID_REGEX: string;

/**
 * Maximum length of the device description string associated with long sessions.
 */
declare var EDAM_DEVICE_DESCRIPTION_LEN_MAX: number;

/**
 * Regular expression for device description strings associated with long sessions.
 */
declare var EDAM_DEVICE_DESCRIPTION_REGEX: string;

/**
 * Maximum number of search suggestions that can be returned
 */
declare var EDAM_SEARCH_SUGGESTIONS_MAX: number;

/**
 * Maximum length of the search suggestion prefix
 */
declare var EDAM_SEARCH_SUGGESTIONS_PREFIX_LEN_MAX: number;

/**
 * Minimum length of the search suggestion prefix
 */
declare var EDAM_SEARCH_SUGGESTIONS_PREFIX_LEN_MIN: number;

/**
 * Default maximum number of results the service will return for findContact
 */
declare var EDAM_FIND_CONTACT_DEFAULT_MAX_RESULTS: number;

/**
 * Absolute maximum number of results the service will return for findContact
 */
declare var EDAM_FIND_CONTACT_MAX_RESULTS: number;

/**
 * The maximum number of separate notes that may be queried in a single call to
 * NoteStore.getViewersForNotes.
 */
declare var EDAM_NOTE_LOCK_VIEWERS_NOTES_MAX: number;

/**
 * Absolute maximum number of results the servce will return for PersistentInternalMarket.getOrders()
 */
declare var EDAM_GET_ORDERS_MAX_RESULTS: number;

/**
 * The maximum length of a message body in unicode characters.
 */
declare var EDAM_MESSAGE_BODY_LEN_MAX: number;

/**
 * The regex to validate message.body against
 */
declare var EDAM_MESSAGE_BODY_REGEX: string;

/**
 * The maximum number of recipients on a MessageThread.
 */
declare var EDAM_MESSAGE_RECIPIENTS_MAX: number;

/**
 * The maximum number of attachments a Message can have.
 */
declare var EDAM_MESSAGE_ATTACHMENTS_MAX: number;

/**
 * The maximum length of a message attachment title in unicode characters.
 */
declare var EDAM_MESSAGE_ATTACHMENT_TITLE_LEN_MAX: number;

/**
 * The regex to validate message attachment titles against
 */
declare var EDAM_MESSAGE_ATTACHMENT_TITLE_REGEX: string;

/**
 * The maximum length of a message attachment snippet in unicode characters.
 */
declare var EDAM_MESSAGE_ATTACHMENT_SNIPPET_LEN_MAX: number;

/**
 * The regex to validate message attachment snippets against
 */
declare var EDAM_MESSAGE_ATTACHMENT_SNIPPET_REGEX: string;

/**
 * Maximum user profile photo size, in bytes, that clients may send to the service.
 * Photos may be resized before being stored on the service.
 */
declare var EDAM_USER_PROFILE_PHOTO_MAX_BYTES: number;

/**
 * The maximum length of a promotion ID in unicode characters.
 */
declare var EDAM_PROMOTION_ID_LEN_MAX: number;

/**
 * The regex to validate promotion IDs against.
 */
declare var EDAM_PROMOTION_ID_REGEX: string;

/**
 * App Feedback Rating range
 */
declare var EDAM_APP_RATING_MIN: number;

declare var EDAM_APP_RATING_MAX: number;

/**
 * The maximium number of note snippets you can retrieve in a single request
 */
declare var EDAM_SNIPPETS_NOTES_MAX: number;

/**
 * The maximum number of connected identities a client can request.
 */
declare var EDAM_CONNECTED_IDENTITY_REQUEST_MAX: number;

/**
 * Maximum length for OpenID token. There is no official enforced limit. The length of the Token ID depends
 * on the provider. 1000 seems to be the safest value at this time.
 */
declare var EDAM_OPEN_ID_ACCESS_TOKEN_MAX: number;
