//
// Autogenerated by Thrift Compiler (0.22.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import thrift = require('thrift');
import Thrift = thrift.Thrift;
import Q = thrift.Q;
import Int64 = require('node-int64');
import UserStore_ttypes = require('./UserStore_types.js');
import Types_ttypes = require('./Types_types.js');
import Errors_ttypes = require('./Errors_types.js');
import Limits_ttypes = require('./Limits_types.js');



/**
 * Privilege levels for accessing shared notebooks.
 * 
 * READ_NOTEBOOK: Recipient is able to read the contents of the shared notebook
 *   but does not have access to information about other recipients of the
 *   notebook or the activity stream information.
 * 
 * READ_NOTEBOOK_PLUS_ACTIVITY: Recipient has READ_NOTEBOOK rights and can also
 *   access information about other recipients and the activity stream.
 * 
 * MODIFY_NOTEBOOK_PLUS_ACTIVITY: Recipient has rights to read and modify the contents
 *   of the shared notebook, including the right to move notes to the trash and to create
 *   notes in the notebook.  The recipient can also access information about other
 *   recipients and the activity stream.
 * 
 * FULL_ACCESS: Recipient has full rights to the shared notebook and recipient lists,
 *   including privilege to revoke and create invitations and to change privilege
 *   levels on invitations for individuals. If the user is a member of the same group,
 *   (e.g. the same business) as the shared notebook, they will additionally be granted
 *   permissions to update the publishing status of the notebook.
 */
declare enum ShareRelationshipPrivilegeLevel {
  READ_NOTEBOOK = 0,
  READ_NOTEBOOK_PLUS_ACTIVITY = 10,
  MODIFY_NOTEBOOK_PLUS_ACTIVITY = 20,
  FULL_ACCESS = 30,
}

/**
 * This structure encapsulates the information about the state of the
 * user's account for the purpose of "state based" synchronization.
 * <dl>
 * <dt>currentTime</dt>
 *   <dd>
 *   The server's current date and time.
 *   </dd>
 * <dt>fullSyncBefore</dt>
 *   <dd>
 *   The cutoff date and time for client caches to be
 *   updated via incremental synchronization.  Any clients that were last
 *   synched with the server before this date/time must do a full resync of all
 *   objects.  This cutoff point will change over time as archival data is
 *   deleted or special circumstances on the service require resynchronization.
 *   </dd>
 * <dt>updateCount</dt>
 *   <dd>
 *   Indicates the total number of transactions that have
 *   been committed within the account.  This reflects (for example) the
 *   number of discrete additions or modifications that have been made to
 *   the data in this account (tags, notes, resources, etc.).
 *   This number is the "high water mark" for Update Sequence Numbers (USN)
 *   within the account.
 *   </dd>
 * <dt>uploaded</dt>
 *   <dd>
 *   The total number of bytes that have been uploaded to
 *   this account in the current monthly period.  This can be compared against
 *   Accounting.uploadLimit (from the UserStore) to determine how close the user
 *   is to their monthly upload limit.
 *   This value may not be present if the SyncState has been retrieved by
 *   a caller that only has read access to the account.
 *   </dd>
 * <dt>userLastUpdated</dt>
 *   <dd>
 *   The last time when a user's account level information was changed. This value
 *   is the latest time when a modification was made to any of the following:
 *   accounting information (billing, quota, premium status, etc.), user attributes
 *   and business user information (business name, business user attributes, etc.) if
 *   the user is in a business.
 *   Clients who need to maintain account information about a User should watch this
 *   field for updates rather than polling UserStore.getUser for updates. Here is the
 *   basic flow that clients should follow:
 *   <ol>
 *     <li>Call NoteStore.getSyncState to retrieve the SyncState object</li>
 *     <li>Compare SyncState.userLastUpdated to previously stored value:
 *         if (SyncState.userLastUpdated > previousValue)
 *           call UserStore.getUser to get the latest User object;
 *         else
 *           do nothing;</li>
 *     <li>Update previousValue = SyncState.userLastUpdated</li>
 *   </ol>
 *   </dd>
 * <dt>userMaxMessageEventId</dt>
 *   <dd>
 *   The greatest MessageEventID for this user's account. Clients that do a full
 *   sync should store this value locally and compare their local copy to the
 *   value returned by getSyncState to determine if they need to sync with
 *   MessageStore. This value will be omitted if the user has never sent or
 *   received a message.
 *   </dd>
 * </dl>
 */
declare class SyncState {
  public currentTime: Int64;
  public fullSyncBefore: Int64;
  public updateCount: number;
  public uploaded?: Int64;
  public userLastUpdated?: Int64;
  public userMaxMessageEventId?: Int64;

    constructor(args?: { currentTime: Int64; fullSyncBefore: Int64; updateCount: number; uploaded?: Int64; userLastUpdated?: Int64; userMaxMessageEventId?: Int64; });
}

/**
 *  This structure is given out by the NoteStore when a client asks to
 *  receive the current state of an account.  The client asks for the server's
 *  state one chunk at a time in order to allow clients to retrieve the state
 *  of a large account without needing to transfer the entire account in
 *  a single message.
 * 
 *  The server always gives SyncChunks using an ascending series of Update
 *  Sequence Numbers (USNs).
 * 
 * <dl>
 *  <dt>currentTime</dt>
 *    <dd>
 *    The server's current date and time.
 *    </dd>
 * 
 *  <dt>chunkHighUSN</dt>
 *    <dd>
 *    The highest USN for any of the data objects represented
 *    in this sync chunk.  If there are no objects in the chunk, this will not be
 *    set.
 *    </dd>
 * 
 *  <dt>updateCount</dt>
 *    <dd>
 *    The total number of updates that have been performed in
 *    the service for this account.  This is equal to the highest USN within the
 *    account at the point that this SyncChunk was generated.  If updateCount
 *    and chunkHighUSN are identical, that means that this is the last chunk
 *    in the account ... there is no more recent information.
 *    </dd>
 * 
 *  <dt>notes</dt>
 *    <dd>
 *    If present, this is a list of non-expunged notes that
 *    have a USN in this chunk.  This will include notes that are "deleted"
 *    but not expunged (i.e. in the trash).  The notes will include their list
 *    of tags and resources, but the note content, resource content, resource
 *    recognition data and resource alternate data will not be supplied.
 *    </dd>
 * 
 *  <dt>notebooks</dt>
 *    <dd>
 *    If present, this is a list of non-expunged notebooks that
 *    have a USN in this chunk.
 *    </dd>
 * 
 *  <dt>tags</dt>
 *    <dd>
 *    If present, this is a list of the non-expunged tags that have a
 *    USN in this chunk.
 *    </dd>
 * 
 *  <dt>searches</dt>
 *    <dd>
 *    If present, this is a list of non-expunged searches that
 *    have a USN in this chunk.
 *    </dd>
 * 
 *  <dt>resources</dt>
 *    <dd>
 *    If present, this is a list of the non-expunged resources
 *    that have a USN in this chunk.  This will include the metadata for each
 *    resource, but not its binary contents or recognition data, which must be
 *    retrieved separately.
 *    </dd>
 * 
 *  <dt>expungedNotes</dt>
 *    <dd>
 *    If present, the GUIDs of all of the notes that were
 *    permanently expunged in this chunk.
 *    </dd>
 * 
 *  <dt>expungedNotebooks</dt>
 *    <dd>
 *    If present, the GUIDs of all of the notebooks that
 *    were permanently expunged in this chunk.  When a notebook is expunged,
 *    this implies that all of its child notes (and their resources) were
 *    also expunged.
 *    </dd>
 * 
 *  <dt>expungedTags</dt>
 *    <dd>
 *    If present, the GUIDs of all of the tags that were
 *    permanently expunged in this chunk.
 *    </dd>
 * 
 *  <dt>expungedSearches</dt>
 *    <dd>
 *    If present, the GUIDs of all of the saved searches
 *    that were permanently expunged in this chunk.
 *    </dd>
 * 
 *  <dt>linkedNotebooks</dt>
 *    <dd>
 *    If present, this is a list of non-expunged LinkedNotebooks that
 *    have a USN in this chunk.
 *    </dd>
 * 
 *  <dt>expungedLinkedNotebooks</dt>
 *    <dd>
 *    If present, the GUIDs of all of the LinkedNotebooks
 *    that were permanently expunged in this chunk.
 *    </dd>
 */
declare class SyncChunk {
  public currentTime: Int64;
  public chunkHighUSN?: number;
  public updateCount: number;
  public notes?: Types_ttypes.Note[];
  public notebooks?: Types_ttypes.Notebook[];
  public tags?: Types_ttypes.Tag[];
  public searches?: Types_ttypes.SavedSearch[];
  public resources?: Types_ttypes.Resource[];
  public expungedNotes?: string[];
  public expungedNotebooks?: string[];
  public expungedTags?: string[];
  public expungedSearches?: string[];
  public linkedNotebooks?: Types_ttypes.LinkedNotebook[];
  public expungedLinkedNotebooks?: string[];

    constructor(args?: { currentTime: Int64; chunkHighUSN?: number; updateCount: number; notes?: Types_ttypes.Note[]; notebooks?: Types_ttypes.Notebook[]; tags?: Types_ttypes.Tag[]; searches?: Types_ttypes.SavedSearch[]; resources?: Types_ttypes.Resource[]; expungedNotes?: string[]; expungedNotebooks?: string[]; expungedTags?: string[]; expungedSearches?: string[]; linkedNotebooks?: Types_ttypes.LinkedNotebook[]; expungedLinkedNotebooks?: string[]; });
}

/**
 *  This structure is used with the 'getFilteredSyncChunk' call to provide
 *  fine-grained control over the data that's returned when a client needs
 *  to synchronize with the service. Each flag in this structure specifies
 *  whether to include one class of data in the results of that call.
 * 
 * <dl>
 *  <dt>includeNotes</dt>
 *    <dd>
 *    If true, then the server will include the SyncChunks.notes field
 *    </dd>
 * 
 *  <dt>includeNoteResources</dt>
 *    <dd>
 *    If true, then the server will include the 'resources' field on all of
 *    the Notes that are in SyncChunk.notes.
 *    If 'includeNotes' is false, then this will have no effect.
 *    </dd>
 * 
 *  <dt>includeNoteAttributes</dt>
 *    <dd>
 *    If true, then the server will include the 'attributes' field on all of
 *    the Notes that are in SyncChunks.notes.
 *    If 'includeNotes' is false, then this will have no effect.
 *    </dd>
 * 
 *  <dt>includeNotebooks</dt>
 *    <dd>
 *    If true, then the server will include the SyncChunks.notebooks field
 *    </dd>
 * 
 *  <dt>includeTags</dt>
 *    <dd>
 *    If true, then the server will include the SyncChunks.tags field
 *    </dd>
 * 
 *  <dt>includeSearches</dt>
 *    <dd>
 *    If true, then the server will include the SyncChunks.searches field
 *    </dd>
 * 
 *  <dt>includeResources</dt>
 *    <dd>
 *    If true, then the server will include the SyncChunks.resources field.
 *    Since the Resources are also provided with their Note
 *    (in the Notes.resources list), this is primarily useful for clients that
 *    want to watch for changes to individual Resources due to recognition data
 *    being added.
 *    </dd>
 * 
 *  <dt>includeLinkedNotebooks</dt>
 *    <dd>
 *    If true, then the server will include the SyncChunks.linkedNotebooks field.
 *    </dd>
 * 
 *  <dt>includeExpunged</dt>
 *    <dd>
 *    If true, then the server will include the 'expunged' data for any type
 *    of included data.  For example, if 'includeTags' and 'includeExpunged'
 *    are both true, then the SyncChunks.expungedTags field will be set with
 *    the GUIDs of tags that have been expunged from the server.
 *    </dd>
 * 
 *  <dt>includeNoteApplicationDataFullMap</dt>
 *    <dd>
 *    If true, then the values for the applicationData map will be filled
 *    in, assuming notes and note attributes are being returned.  Otherwise,
 *    only the keysOnly field will be filled in.
 *    </dd>
 * 
 *  <dt>includeResourceApplicationDataFullMap</dt>
 *    <dd>
 *    If true, then the fullMap values for the applicationData map will be
 *    filled in, assuming resources and resource attributes are being returned
 *    (includeResources is true).  Otherwise, only the keysOnly field will be
 *    filled in.
 *    </dd>
 * 
 *  <dt>includeNoteResourceApplicationDataFullMap</dt>
 *    <dd>
 *    If true, then the fullMap values for the applicationData map will be
 *    filled in for resources found inside of notes, assuming resources are
 *    being returned in notes (includeNoteResources is true).  Otherwise,
 *    only the keysOnly field will be filled in.
 *    </dd>
 * 
 *  <dt>omitSharedNotebooks<dt>
 *    <dd>
 *    Normally, if 'includeNotebooks' is true, then the SyncChunks will
 *    include Notebooks that may include a set of SharedNotebook
 *    invitations via Notebook.sharedNotebookIds and Notebook.sharedNotebooks.
 *    However, if omitSharedNotebooks is set to true, then the Notebooks
 *    will omit those two fields and leave them unset. This should be used
 *    by clients who want to know their own set of Notebooks (and the
 *    associated permissions via Notebook.recipientSettings), and who
 *    do not need to know the full set of other people who can also see
 *    that same notebook.
 *    </dd>
 * 
 *  <dt>requireNoteContentClass</dt>
 *    <dd>
 *    If set, then only send notes whose content class matches this value.
 *    The value can be a literal match or, if the last character is an
 *    asterisk, a prefix match.
 *    </dd>
 * 
 *  <dt>notebookGuids</dt>
 *    <dd>
 *    If set, then restrict the returned notebooks, notes, and
 *    resources to those associated with one of the notebooks whose
 *    GUID is provided in this list.  If not set, then no filtering on
 *    notebook GUID will be performed.  If you set this field, you may
 *    not also set includeExpunged else an EDAMUserException with an
 *    error code of DATA_CONFLICT will be thrown.  You only need to set
 *    this field if you want to restrict the returned entities more
 *    than what your authentication token allows you to access.  For
 *    example, there is no need to set this field for single notebook
 *    tokens such as for shared notebooks.  You can use this field to
 *    synchronize a newly discovered business notebook while
 *    incrementally synchronizing a business account, in which case you
 *    will only need to consider setting includeNotes,
 *    includeNotebooks, includeNoteAttributes, includeNoteResources,
 *    and maybe some of the "FullMap" fields.
 *    </dd>
 * 
 *  <dt>includeSharedNotes</dt>
 *    <dd>
 *    If true, then the service will include the sharedNotes field on all
 *    notes that are in SyncChunk.notes. If 'includeNotes' is false, then
 *    this will have no effect.
 *    </dd>
 *  </dl>
 */
declare class SyncChunkFilter {
  public includeNotes?: boolean;
  public includeNoteResources?: boolean;
  public includeNoteAttributes?: boolean;
  public includeNotebooks?: boolean;
  public includeTags?: boolean;
  public includeSearches?: boolean;
  public includeResources?: boolean;
  public includeLinkedNotebooks?: boolean;
  public includeExpunged?: boolean;
  public includeNoteApplicationDataFullMap?: boolean;
  public includeResourceApplicationDataFullMap?: boolean;
  public includeNoteResourceApplicationDataFullMap?: boolean;
  public includeSharedNotes?: boolean;
  public omitSharedNotebooks?: boolean;
  public requireNoteContentClass?: string;
  public notebookGuids?: string[];

    constructor(args?: { includeNotes?: boolean; includeNoteResources?: boolean; includeNoteAttributes?: boolean; includeNotebooks?: boolean; includeTags?: boolean; includeSearches?: boolean; includeResources?: boolean; includeLinkedNotebooks?: boolean; includeExpunged?: boolean; includeNoteApplicationDataFullMap?: boolean; includeResourceApplicationDataFullMap?: boolean; includeNoteResourceApplicationDataFullMap?: boolean; includeSharedNotes?: boolean; omitSharedNotebooks?: boolean; requireNoteContentClass?: string; notebookGuids?: string[]; });
}

/**
 *  A list of criteria that are used to indicate which notes are desired from
 *  the account.  This is used in queries to the NoteStore to determine
 *  which notes should be retrieved.
 * 
 * <dl>
 *  <dt>order</dt>
 *    <dd>
 *    The NoteSortOrder value indicating what criterion should be
 *    used to sort the results of the filter.
 *    </dd>
 * 
 *  <dt>ascending</dt>
 *    <dd>
 *    If true, the results will be ascending in the requested
 *    sort order.  If false, the results will be descending.
 *    </dd>
 * 
 *  <dt>words</dt>
 *    <dd>
 *    If present, a search query string that will filter the set of notes to be returned.
 *    Accepts the full search grammar documented in the Evernote API Overview.
 *    </dd>
 * 
 *  <dt>notebookGuid</dt>
 *    <dd>
 *    If present, the Guid of the notebook that must contain
 *    the notes.
 *    </dd>
 * 
 *  <dt>tagGuids</dt>
 *    <dd>
 *    If present, the list of tags (by GUID) that must be present
 *    on the notes.
 *    </dd>
 * 
 *  <dt>timeZone</dt>
 *    <dd>
 *    The zone ID for the user, which will be used to interpret
 *    any dates or times in the queries that do not include their desired zone
 *    information.
 *    For example, if a query requests notes created "yesterday", this
 *    will be evaluated from the provided time zone, if provided.
 *    The format must be encoded as a standard zone ID such as
 *    "America/Los_Angeles".
 *    </dd>
 * 
 *  <dt>inactive</dt>
 *    <dd>
 *    If true, then only notes that are not active (i.e. notes in
 *    the Trash) will be returned. Otherwise, only active notes will be returned.
 *    There is no way to find both active and inactive notes in a single query.
 *    </dd>
 * 
 *  <dt>emphasized</dt>
 *    <dd>
 *    If present, a search query string that may or may not influence the notes
 *    to be returned, both in terms of coverage as well as of order. Think of it
 *    as a wish list, not a requirement.
 *    Accepts the full search grammar documented in the Evernote API Overview.
 *    </dd>
 * 
 *  <dt>includeAllReadableNotebooks</dt>
 *    <dd>
 *    If true, then the search will include all business notebooks that are readable
 *    by the user. A business authentication token must be supplied for
 *    this option to take effect when calling search APIs.
 *    </dd>
 * 
 *  <dt>includeAllReadableWorkspaces</dt>
 *    <dd>
 *    If true, then the search will include all workspaces that are readable
 *    by the user. A business authentication token must be supplied for
 *    this option to take effect when calling search APIs.
 *    </dd>
 * 
 *  <dt>context</dt>
 *    <dd>
 *    Specifies the context to consider when determining result ranking.
 *    Clients must leave this value unset unless they wish to explicitly specify a known
 *    non-default context.
 *    </dd>
 * 
 *  <dt>rawWords</dt>
 *    <dd>
 *    If present, the raw user query input.
 *    Accepts the full search grammar documented in the Evernote API Overview.
 *    </dd>
 * 
 *  <dt>searchContextBytes</dt>
 *    <dd>
 *    Specifies the correlating information about the current search session, in byte array.
 *    If this request is not for the first page of search results, the client should populate
 *    this field with the value of searchContextBytes from the NotesMetadataList of the
 *    original search response.
 *    </dd>
 *  </dl>
 */
declare class NoteFilter {
  public order?: number;
  public ascending?: boolean;
  public words?: string;
  public notebookGuid?: string;
  public tagGuids?: string[];
  public timeZone?: string;
  public inactive?: boolean;
  public emphasized?: string;
  public includeAllReadableNotebooks?: boolean;
  public includeAllReadableWorkspaces?: boolean;
  public context?: string;
  public rawWords?: string;
  public searchContextBytes?: Buffer;

    constructor(args?: { order?: number; ascending?: boolean; words?: string; notebookGuid?: string; tagGuids?: string[]; timeZone?: string; inactive?: boolean; emphasized?: string; includeAllReadableNotebooks?: boolean; includeAllReadableWorkspaces?: boolean; context?: string; rawWords?: string; searchContextBytes?: Buffer; });
}

/**
 *  A small structure for returning a list of notes out of a larger set.
 * 
 * <dl>
 *  <dt>startIndex</dt>
 *    <dd>
 *    The starting index within the overall set of notes.  This
 *    is also the number of notes that are "before" this list in the set.
 *    </dd>
 * 
 *  <dt>totalNotes</dt>
 *    <dd>
 *    The number of notes in the larger set.  This can be used
 *    to calculate how many notes are "after" this note in the set.
 *    (I.e.  remaining = totalNotes - (startIndex + notes.length)  )
 *    </dd>
 * 
 *  <dt>notes</dt>
 *    <dd>
 *    The list of notes from this range.  The Notes will include all
 *    metadata (attributes, resources, etc.), but will not include the ENML
 *    content of the note or the binary contents of any resources.
 *    </dd>
 * 
 *  <dt>stoppedWords</dt>
 *    <dd>
 *    If the NoteList was produced using a text based search
 *    query that included words that are not indexed or searched by the service,
 *    this will include a list of those ignored words.
 *    </dd>
 * 
 *  <dt>searchedWords</dt>
 *    <dd>
 *    If the NoteList was produced using a text based search
 *    query that included viable search words or quoted expressions, this will
 *    include a list of those words.  Any stopped words will not be included
 *    in this list.
 *    </dd>
 * 
 *  <dt>updateCount</dt>
 *    <dd>
 *    Indicates the total number of transactions that have
 *    been committed within the account.  This reflects (for example) the
 *    number of discrete additions or modifications that have been made to
 *    the data in this account (tags, notes, resources, etc.).
 *    This number is the "high water mark" for Update Sequence Numbers (USN)
 *    within the account.
 *    </dd>
 * 
 *  <dt>searchContextBytes</dt>
 *    <dd>
 *    Specifies the correlating information about the current search session, in byte array.
 *    </dd>
 *  </dl>
 * 
 *  <dt>debugInfo</dt>
 *    <dd>
 *    Depends on the value of <code>context</code> in NoteFilter, this field
 *    may contain debug information if the service decides to do so.
 *    </dd>
 * 
 */
declare class NoteList {
  public startIndex: number;
  public totalNotes: number;
  public notes: Types_ttypes.Note[];
  public stoppedWords?: string[];
  public searchedWords?: string[];
  public updateCount?: number;
  public searchContextBytes?: Buffer;
  public debugInfo?: string;

    constructor(args?: { startIndex: number; totalNotes: number; notes: Types_ttypes.Note[]; stoppedWords?: string[]; searchedWords?: string[]; updateCount?: number; searchContextBytes?: Buffer; debugInfo?: string; });
}

/**
 * This structure is used in the set of results returned by the
 * findNotesMetadata function.  It represents the high-level information about
 * a single Note, without some of the larger deep structure.  This allows
 * for the information about a list of Notes to be returned relatively quickly
 * with less marshalling and data transfer to remote clients.
 * Most fields in this structure are identical to the corresponding field in
 * the Note structure, with the exception of:
 * 
 * <dl>
 * <dt>largestResourceMime</dt>
 *   <dd>If set, then this will contain the MIME type of the largest Resource
 *   (in bytes) within the Note.  This may be useful, for example, to choose
 *   an appropriate icon or thumbnail to represent the Note.
 *   </dd>
 * 
 * <dt>largestResourceSize</dt>
 *  <dd>If set, this will contain the size of the largest Resource file, in
 *  bytes, within the Note.  This may be useful, for example, to decide whether
 *  to ask the server for a thumbnail to represent the Note.
 *  </dd>
 * </dl>
 */
declare class NoteMetadata {
  public guid: string;
  public title?: string;
  public contentLength?: number;
  public created?: Int64;
  public updated?: Int64;
  public deleted?: Int64;
  public updateSequenceNum?: number;
  public notebookGuid?: string;
  public tagGuids?: string[];
  public attributes?: Types_ttypes.NoteAttributes;
  public largestResourceMime?: string;
  public largestResourceSize?: number;

    constructor(args?: { guid: string; title?: string; contentLength?: number; created?: Int64; updated?: Int64; deleted?: Int64; updateSequenceNum?: number; notebookGuid?: string; tagGuids?: string[]; attributes?: Types_ttypes.NoteAttributes; largestResourceMime?: string; largestResourceSize?: number; });
}

/**
 *  This structure is returned from calls to the findNotesMetadata function to
 *  give the high-level metadata about a subset of Notes that are found to
 *  match a specified NoteFilter in a search.
 * 
 * <dl>
 *  <dt>startIndex</dt>
 *    <dd>
 *    The starting index within the overall set of notes.  This
 *    is also the number of notes that are "before" this list in the set.
 *    </dd>
 * 
 *  <dt>totalNotes</dt>
 *    <dd>
 *    The number of notes in the larger set.  This can be used
 *    to calculate how many notes are "after" this note in the set.
 *    (I.e.  remaining = totalNotes - (startIndex + notes.length)  )
 *    </dd>
 * 
 *  <dt>notes</dt>
 *    <dd>
 *    The list of metadata for Notes in this range.  The set of optional fields
 *    that are set in each metadata structure will depend on the
 *    NotesMetadataResultSpec provided by the caller when the search was
 *    performed.  Only the 'guid' field will be guaranteed to be set in each
 *    Note.
 *    </dd>
 * 
 *  <dt>stoppedWords</dt>
 *    <dd>
 *    If the NoteList was produced using a text based search
 *    query that included words that are not indexed or searched by the service,
 *    this will include a list of those ignored words.
 *    </dd>
 * 
 *  <dt>searchedWords</dt>
 *    <dd>
 *    If the NoteList was produced using a text based search
 *    query that included viable search words or quoted expressions, this will
 *    include a list of those words.  Any stopped words will not be included
 *    in this list.
 *    </dd>
 * 
 *  <dt>updateCount</dt>
 *    <dd>
 *    Indicates the total number of transactions that have
 *    been committed within the account.  This reflects (for example) the
 *    number of discrete additions or modifications that have been made to
 *    the data in this account (tags, notes, resources, etc.).
 *    This number is the "high water mark" for Update Sequence Numbers (USN)
 *    within the account.
 *    </dd>
 * 
 *  <dt>searchContextBytes</dt>
 *    <dd>
 *    Specifies the correlating information about the current search session, in byte array.
 *    </dd>
 * 
 *  <dt>debugInfo</dt>
 *    <dd>
 *    Depends on the value of <code>context</code> in NoteFilter, this field
 *    may contain debug information if the service decides to do so.
 *    </dd>
 * 
 *  </dl>
 */
declare class NotesMetadataList {
  public startIndex: number;
  public totalNotes: number;
  public notes: NoteMetadata[];
  public stoppedWords?: string[];
  public searchedWords?: string[];
  public updateCount?: number;
  public searchContextBytes?: Buffer;
  public debugInfo?: string;

    constructor(args?: { startIndex: number; totalNotes: number; notes: NoteMetadata[]; stoppedWords?: string[]; searchedWords?: string[]; updateCount?: number; searchContextBytes?: Buffer; debugInfo?: string; });
}

/**
 * This structure is provided to the findNotesMetadata function to specify
 * the subset of fields that should be included in each NoteMetadata element
 * that is returned in the NotesMetadataList.
 * Each field on this structure is a boolean flag that indicates whether the
 * corresponding field should be included in the NoteMetadata structure when
 * it is returned.  For example, if the 'includeTitle' field is set on this
 * structure when calling findNotesMetadata, then each NoteMetadata in the
 * list should have its 'title' field set.
 * If one of the fields in this spec is not set, then it will be treated as
 * 'false' by the server, so the default behavior is to include nothing in
 * replies (but the mandatory GUID)
 */
declare class NotesMetadataResultSpec {
  public includeTitle?: boolean;
  public includeContentLength?: boolean;
  public includeCreated?: boolean;
  public includeUpdated?: boolean;
  public includeDeleted?: boolean;
  public includeUpdateSequenceNum?: boolean;
  public includeNotebookGuid?: boolean;
  public includeTagGuids?: boolean;
  public includeAttributes?: boolean;
  public includeLargestResourceMime?: boolean;
  public includeLargestResourceSize?: boolean;

    constructor(args?: { includeTitle?: boolean; includeContentLength?: boolean; includeCreated?: boolean; includeUpdated?: boolean; includeDeleted?: boolean; includeUpdateSequenceNum?: boolean; includeNotebookGuid?: boolean; includeTagGuids?: boolean; includeAttributes?: boolean; includeLargestResourceMime?: boolean; includeLargestResourceSize?: boolean; });
}

/**
 *  A data structure representing the number of notes for each notebook
 *  and tag with a non-zero set of applicable notes.
 * 
 * <dl>
 *  <dt>notebookCounts</dt>
 *    <dd>
 *    A mapping from the Notebook GUID to the number of
 *    notes (from some selection) that are in the corresponding notebook.
 *    </dd>
 * 
 *  <dt>tagCounts</dt>
 *    <dd>
 *    A mapping from the Tag GUID to the number of notes (from some
 *    selection) that have the corresponding tag.
 *    </dd>
 * 
 *  <dt>trashCount</dt>
 *    <dd>
 *    If this is set, then this is the number of notes that are in the trash.
 *    If this is not set, then the number of notes in the trash hasn't been
 *    reported.  (I.e. if there are no notes in the trash, this will be set
 *    to 0.)
 *    </dd>
 *  </dl>
 */
declare class NoteCollectionCounts {
  public notebookCounts?: { [k: string]: number; };
  public tagCounts?: { [k: string]: number; };
  public trashCount?: number;

    constructor(args?: { notebookCounts?: { [k: string]: number; }; tagCounts?: { [k: string]: number; }; trashCount?: number; });
}

/**
 * This structure is provided to the getNoteWithResultSpec function to specify the subset of
 * fields that should be included in the Note that is returned. This allows clients to request
 * the minimum set of information that they require when retrieving a note, reducing the size
 * of the response and improving the response time.
 * 
 * If one of the fields in this spec is not set, then it will be treated as 'false' by the service,
 * so that the default behavior is to include none of the fields below in the Note.
 * 
 * <dl>
 *   <dt>includeContent</dt>
 *   <dd>If true, the Note.content field will be populated with the note's ENML contents.</dd>
 * 
 *   <dt>includeResourcesData</dt>
 *   <dd>If true, any Resource elements will include the binary contents of their 'data' field's
 *     body.</dd>
 * 
 *   <dt>includeResourcesRecognition</dt>
 *   <dd>If true, any Resource elements will include the binary contents of their 'recognition'
 *     field's body if recognition data is available.</dd>
 * 
 *   <dt>includeResourcesAlternateData</dt>
 *   <dd>If true, any Resource elements will include the binary contents of their 'alternateData'
 *     field's body, if an alternate form is available.</dd>
 * 
 *   <dt>includeSharedNotes</dt>
 *   <dd>If true, the Note.sharedNotes field will be populated with the note's shares.</dd>
 * 
 *   <dt>includeNoteAppDataValues</dt>
 *   <dd>If true, the Note.attributes.applicationData.fullMap field will be populated.</dd>
 * 
 *   <dt>includeResourceAppDataValues</dt>
 *   <dd>If true, the Note.resource.attributes.applicationData.fullMap field will be populated.</dd>
 * 
 *   <dt>includeAccountLimits</dt>
 *   <dd>If true, the Note.limits field will be populated with the note owner's account limits.</dd>
 * </dl>
 */
declare class NoteResultSpec {
  public includeContent?: boolean;
  public includeResourcesData?: boolean;
  public includeResourcesRecognition?: boolean;
  public includeResourcesAlternateData?: boolean;
  public includeSharedNotes?: boolean;
  public includeNoteAppDataValues?: boolean;
  public includeResourceAppDataValues?: boolean;
  public includeAccountLimits?: boolean;

    constructor(args?: { includeContent?: boolean; includeResourcesData?: boolean; includeResourcesRecognition?: boolean; includeResourcesAlternateData?: boolean; includeSharedNotes?: boolean; includeNoteAppDataValues?: boolean; includeResourceAppDataValues?: boolean; includeAccountLimits?: boolean; });
}

/**
 * Parameters that must be given to the NoteStore emailNote call. These allow
 * the caller to specify the note to send, the recipient addresses, etc.
 * 
 * <dl>
 *  <dt>guid</dt>
 *    <dd>
 *      If set, this must be the GUID of a note within the user's account that
 *      should be retrieved from the service and sent as email.  If not set,
 *      the 'note' field must be provided instead.
 *    </dd>
 * 
 *  <dt>note</dt>
 *    <dd>
 *      If the 'guid' field is not set, this field must be provided, including
 *      the full contents of the note note (and all of its Resources) to send.
 *      This can be used for a Note that as not been created in the service,
 *      for example by a local client with local notes.
 *    </dd>
 * 
 *  <dt>toAddresses</dt>
 *    <dd>
 *      If provided, this should contain a list of the SMTP email addresses
 *      that should be included in the "To:" line of the email.
 *      Callers must specify at least one "to" or "cc" email address.
 *    </dd>
 * 
 *  <dt>ccAddresses</dt>
 *    <dd>
 *      If provided, this should contain a list of the SMTP email addresses
 *      that should be included in the "Cc:" line of the email.
 *      Callers must specify at least one "to" or "cc" email address.
 *    </dd>
 * 
 *  <dt>subject</dt>
 *    <dd>
 *      If provided, this should contain the subject line of the email that
 *      will be sent.  If not provided, the title of the note will be used
 *      as the subject of the email.
 *    </dd>
 * 
 *  <dt>message</dt>
 *    <dd>
 *      If provided, this is additional personal text that should be included
 *      into the email as a message from the owner to the recipient(s).
 *    </dd>
 * </dl>
 */
declare class NoteEmailParameters {
  public guid?: string;
  public note?: Types_ttypes.Note;
  public toAddresses?: string[];
  public ccAddresses?: string[];
  public subject?: string;
  public message?: string;

    constructor(args?: { guid?: string; note?: Types_ttypes.Note; toAddresses?: string[]; ccAddresses?: string[]; subject?: string; message?: string; });
}

/**
 * Identifying information about previous versions of a note that are backed up
 * within Evernote's servers.  Used in the return value of the listNoteVersions
 * call.
 * 
 * <dl>
 *  <dt>updateSequenceNum</dt>
 *  <dd>
 *    The update sequence number for the Note when it last had this content.
 *    This serves to uniquely identify each version of the note, since USN
 *    values are unique within an account for each update.
 *  </dd>
 *  <dt>updated</dt>
 *  <dd>
 *    The 'updated' time that was set on the Note when it had this version
 *    of the content.  This is the user-modifiable modification time on the
 *    note, so it's not reliable for guaranteeing the order of various
 *    versions.  (E.g. if someone modifies the note, then changes this time
 *    manually into the past and then updates the note again.)
 *  </dd>
 *  <dt>saved</dt>
 *  <dd>
 *    A timestamp that holds the date and time when this version of the note
 *    was backed up by Evernote's servers.
 *  </dd>
 *  <dt>title</dt>
 *  <dd>
 *    The title of the note when this particular version was saved.  (The
 *    current title of the note may differ from this value.)
 *  </dd>
 *  <dt>lastEditorId</dt>
 *  <dd>
 *    The ID of the user who made the change to this version of the note. This will be
 *    unset if the note version was edited by the owner of the account.
 *  </dd>
 * </dl>
 */
declare class NoteVersionId {
  public updateSequenceNum: number;
  public updated: Int64;
  public saved: Int64;
  public title: string;
  public lastEditorId?: number;

    constructor(args?: { updateSequenceNum: number; updated: Int64; saved: Int64; title: string; lastEditorId?: number; });
}

/**
 * A description of the thing for which we are searching for related
 * entities.
 * 
 * You must specify either <em>noteGuid</em> or <em>plainText</em>, but
 * not both. <em>filter</em> and <em>referenceUri</em> are optional.
 * 
 * <dl>
 * <dt>noteGuid</dt>
 * <dd>The GUID of an existing note in your account for which related
 *     entities will be found.</dd>
 * 
 * <dt>plainText</dt>
 * <dd>A string of plain text for which to find related entities.
 *     You should provide a text block with a number of characters between
 *     EDAM_RELATED_PLAINTEXT_LEN_MIN and EDAM_RELATED_PLAINTEXT_LEN_MAX.
 *     </dd>
 * 
 * <dt>filter</dt>
 * <dd>The list of criteria that will constrain the notes being considered
 *     related.
 *     Please note that some of the parameters may be ignored, such as
 *     <em>order</em> and <em>ascending</em>.
 * </dd>
 * 
 * <dt>referenceUri</dt>
 * <dd>A URI string specifying a reference entity, around which "relatedness"
 *     should be based. This can be an URL pointing to a web page, for example.
 * </dd>
 * 
 * <dt>context</dt>
 * <dd>Specifies the context to consider when determining related results.
 *     Clients must leave this value unset unless they wish to explicitly specify a known
 *     non-default context.
 * </dd>
 * 
 * <dt>cacheKey</dt>
 * <dd>If set and non-empty, this is an indicator for the server whether it is actually
 *     necessary to perform a new findRelated call at all. Cache Keys are opaque strings
 *     which are returned by the server as part of "RelatedResult" in response
 *     to a "NoteStore.findRelated" query. Cache Keys are inherently query specific.
 * 
 *     If set to an empty string, this indicates that the server should generate a cache
 *     key in the response as part of "RelatedResult".
 * 
 *     If not set, the server will not attempt to generate a cache key at all.
 * </dd>
 * </dl>
 */
declare class RelatedQuery {
  public noteGuid?: string;
  public plainText?: string;
  public filter?: NoteFilter;
  public referenceUri?: string;
  public context?: string;
  public cacheKey?: string;

    constructor(args?: { noteGuid?: string; plainText?: string; filter?: NoteFilter; referenceUri?: string; context?: string; cacheKey?: string; });
}

/**
 * The result of calling findRelated().  The contents of the notes,
 * notebooks, and tags fields will be in decreasing order of expected
 * relevance.  It is possible that fewer results than requested will be
 * returned even if there are enough distinct entities in the account
 * in cases where the relevance is estimated to be low.
 * 
 * <dl>
 * <dt>notes</dt>
 * <dd>If notes have been requested to be included, this will be the
 *     list of notes.</dd>
 * 
 * <dt>notebooks</dt>
 * <dd>If notebooks have been requested to be included, this will be the
 *     list of notebooks.</dd>
 * 
 * <dt>tags</dt>
 * <dd>If tags have been requested to be included, this will be the list
 *     of tags.</dd>
 * 
 * <dt>containingNotebooks</dt>
 * <dd>If <code>includeContainingNotebooks</code> is set to <code>true</code>
 *     in the RelatedResultSpec, return the list of notebooks to
 *     to which the returned related notes belong. The notebooks in this
 *     list will occur once per notebook GUID and are represented as
 *     NotebookDescriptor objects.</dd>
 * 
 * <dt>experts</dt>
 * <dd>If experts have been requested to be included, this will return
 *  a list of users within your business who have knowledge about the specified query.
 * </dd>
 * 
 * <dt>relatedContent</dt>
 * <dd>If related content has been requested to be included, this will be the list of
 *  related content snippets.
 * </dd>
 * 
 * <dt>cacheKey</dt>
 * <dd>If set and non-empty, this cache key may be used in subsequent
 *     "NoteStore.findRelated" calls (via "RelatedQuery") to re-use previous
 *     responses that were cached on the client-side, instead of actually performing
 *     another search.
 * 
 *     If set to an empty string, this indicates that the server could not determine
 *     a specific key for this response, but the client should nevertheless remove
 *     any previously cached result for this request.
 * 
 *     If unset/null, it is up to the client whether to re-use cached results or to
 *     use the server's response.
 * 
 *     If set to the exact non-empty cache key that was specified in
 *     "RelatedQuery.cacheKey", this indicates that the server decided that cached results
 *     could be reused.
 * 
 *     Depending on the cache key specified in the query, the "RelatedResult" may only be
 *     partially filled. For each set field, the client should replace the corresponding
 *     part in the previously cached result with the new partial result.
 * 
 *     For example, for a specific query that has both "RelatedResultSpec.maxNotes" and
 *     "RelatedResultSpec.maxRelatedContent" set to positive values, the server may decide
 *     that the previously requested and cached <em>Related Content</em> are unchanged,
 *     but new results for <em>Related Notes</em> are available. The
 *     response will have a new cache key and have "RelatedResult.notes" set, but have
 *     "RelatedResult.relatedContent" unset (not just empty, but really unset).
 * 
 *     In this situation, the client should replace any cached notes with the newly
 *     returned "RelatedResult.notes", but it can re-use the previously cached entries for
 *     "RelatedResult.relatedContent". List fields that are set, but empty indicate that
 *     no results could be found; the cache should be updated correspondingly.
 * </dd>
 * 
 * <dt>cacheExpires</dt>
 * <dd> If set, clients should reuse this response for any situations where the same input
 *      parameters are applicable for up to this many seconds after receiving this result.
 * 
 *      After this time has passed, the client may request a new result from the service,
 *      but it should supply the stored cacheKey to the service when checking for an
 *      update.
 * </dd>
 * 
 * </dl>
 */
declare class RelatedResult {
  public notes?: Types_ttypes.Note[];
  public notebooks?: Types_ttypes.Notebook[];
  public tags?: Types_ttypes.Tag[];
  public containingNotebooks?: Types_ttypes.NotebookDescriptor[];
  public debugInfo?: string;
  public experts?: Types_ttypes.UserProfile[];
  public relatedContent?: Types_ttypes.RelatedContent[];
  public cacheKey?: string;
  public cacheExpires?: number;

    constructor(args?: { notes?: Types_ttypes.Note[]; notebooks?: Types_ttypes.Notebook[]; tags?: Types_ttypes.Tag[]; containingNotebooks?: Types_ttypes.NotebookDescriptor[]; debugInfo?: string; experts?: Types_ttypes.UserProfile[]; relatedContent?: Types_ttypes.RelatedContent[]; cacheKey?: string; cacheExpires?: number; });
}

/**
 * A description of the thing for which the service will find related
 * entities, via findRelated(), together with a description of what
 * type of entities and how many you are seeking in the
 * RelatedResult.
 * 
 * <dl>
 * <dt>maxNotes</dt>
 * <dd>Return notes that are related to the query, but no more than
 *     this many.  Any value greater than EDAM_RELATED_MAX_NOTES
 *     will be silently capped.  If you do not set this field, then
 *     no notes will be returned.</dd>
 * 
 * <dt>maxNotebooks</dt>
 * <dd>Return notebooks that are related to the query, but no more than
 *     this many.  Any value greater than EDAM_RELATED_MAX_NOTEBOOKS
 *     will be silently capped.  If you do not set this field, then
 *     no notebooks will be returned.</dd>
 * 
 * <dt>maxTags</dt>
 * <dd>Return tags that are related to the query, but no more than
 *     this many.  Any value greater than EDAM_RELATED_MAX_TAGS
 *     will be silently capped.  If you do not set this field, then
 *     no tags will be returned.</dd>
 * </dl>
 * 
 * <dt>writableNotebooksOnly</dt>
 * <dd>Require that all returned related notebooks are writable.
 *     The user will be able to create notes in all returned notebooks.
 *     However, individual notes returned may still belong to notebooks
 *     in which the user lacks the ability to create notes.</dd>
 * </dl>
 * 
 * <dt>includeContainingNotebooks</dt>
 * <dd>If set to <code>true</code>, return the containingNotebooks field
 *     in the RelatedResult, which will contain the list of notebooks to
 *     to which the returned related notes belong.</dd>
 * </dl>
 * 
 * <dt>includeDebugInfo</dt>
 * <dd>If set to <code>true</code>, indicate that debug information should
 *     be returned in the 'debugInfo' field of RelatedResult. Note that the call may
 *     be slower if this flag is set.</dd>
 * 
 * <dt>maxExperts</dt>
 * <dd>This can only be used when making a findRelated call against a business.
 *  Find users within your business who have knowledge about the specified query.
 *  No more than this many users will be returned. Any value greater than
 *  EDAM_RELATED_MAX_EXPERTS will be silently capped.
 * </dd>
 * 
 * <dt>maxRelatedContent</dt>
 * <dd>Return snippets of related content that is related to the query, but no more than
 *  this many. Any value greater than EDAM_RELATED_MAX_RELATED_CONTENT will be silently
 *  capped. If you do not set this field, then no related content will be returned.</dd>
 * </dl>
 * 
 * <dt>relatedContentTypes</dt>
 * <dd>Specifies the types of Related Content that should be returned.</dd>
 * </dl>
 */
declare class RelatedResultSpec {
  public maxNotes?: number;
  public maxNotebooks?: number;
  public maxTags?: number;
  public writableNotebooksOnly?: boolean;
  public includeContainingNotebooks?: boolean;
  public includeDebugInfo?: boolean;
  public maxExperts?: number;
  public maxRelatedContent?: number;
  public relatedContentTypes?: Types_ttypes.RelatedContentType[];

    constructor(args?: { maxNotes?: number; maxNotebooks?: number; maxTags?: number; writableNotebooksOnly?: boolean; includeContainingNotebooks?: boolean; includeDebugInfo?: boolean; maxExperts?: number; maxRelatedContent?: number; relatedContentTypes?: Types_ttypes.RelatedContentType[]; });
}

/**
 * The result of a call to updateNoteIfUsnMatches, which optionally updates a note
 * based on the current value of the note's update sequence number on the service.
 * 
 * <dl>
 * <dt>note</dt>
 * <dd>Either the current state of the note if <tt>updated</tt> is false or the
 * result of updating the note as would be done via the <tt>updateNote</tt> method.
 * If the note was not updated, you will receive a Note that does not include note
 * content, resources data, resources recognition data, or resources alternate data.
 * You can check for updates to these large objects by checking the Data.bodyHash
 * values and downloading accordingly.</dd>
 * 
 * <dt>updated</dt>
 * <dd>Whether or not the note was updated by the operation.</dd>
 * </dl>
 */
declare class UpdateNoteIfUsnMatchesResult {
  public note?: Types_ttypes.Note;
  public updated?: boolean;

    constructor(args?: { note?: Types_ttypes.Note; updated?: boolean; });
}

declare class ShareRelationshipRestrictions {
  public noSetReadOnly?: boolean;
  public noSetReadPlusActivity?: boolean;
  public noSetModify?: boolean;
  public noSetFullAccess?: boolean;

    constructor(args?: { noSetReadOnly?: boolean; noSetReadPlusActivity?: boolean; noSetModify?: boolean; noSetFullAccess?: boolean; });
}

/**
 * Describes an invitation to a person to use their Evernote
 * credentials to become a member of a notebook.
 * 
 * <dl>
 * <dt>displayName</dt>
 * <dd>The string that clients should show to users to represent this
 * invitation.</dd>
 * 
 * <dt>recipientUserIdentity</dt>
 * <dd>Identifies the recipient of the invitation. The user identity
 * type can be either EMAIL, EVERNOTE or IDENTITYID. If the
 * invitation was created using the classic notebook sharing APIs it will be EMAIL. If it
 * was created using the new identity-based notebook sharing APIs it will either be
 * EVERNOTE or IDENTITYID, depending on whether we can map the identity to an Evernote
 * user at the time of creation.
 * </dd>
 * 
 * <dt>privilege</dt>
 * <dd>The privilege level at which the member will be joined, if it
 * turns out that the member is not already joined at a higher level.
 * Note that the <tt>identity</tt> field may not uniquely identify an
 * Evernote User ID, and so we won't know until the invitation is
 * redeemed whether or not the recipient already has privilege.</dd>
 * 
 * <dt>sharerUserId</dt>
 * <dd>The user id of the user who most recently shared this notebook
 * to this identity. This field is used by the service to convey information
 * to the user, so clients should treat it as read-only.</dd>
 * </dl>
 */
declare class InvitationShareRelationship {
  public displayName?: string;
  public recipientUserIdentity?: Types_ttypes.UserIdentity;
  public privilege?: ShareRelationshipPrivilegeLevel;
  public sharerUserId?: number;

    constructor(args?: { displayName?: string; recipientUserIdentity?: Types_ttypes.UserIdentity; privilege?: ShareRelationshipPrivilegeLevel; sharerUserId?: number; });
}

/**
 * Describes the association between a Notebook and an Evernote User who is
 * a member of that notebook.
 * 
 * <dl>
 * <dt>displayName</dt>
 * <dd>The string that clients should show to users to represent this
 * member.</dd>
 * 
 * <dt>recipientUserId</dt>
 * <dd>The Evernote User ID of the recipient of this notebook share.
 * </dd>
 * 
 * <dt>bestPrivilege</dt>
 * <dd>The privilege at which the member can access the notebook,
 * which is the best privilege granted either individually or to a
 * group to which a member belongs, such as a business.  This field is
 * used by the service to convey information to the user, so clients
 * should treat it as read-only.</dd>
 * 
 * <dt>individualPrivilege</dt>
 * <dd>The individually granted privilege for the member, which does
 * not take GROUP privileges into account.  This value may be unset if
 * only a group-assigned privilege has been granted to the member.
 * This value can be managed by others with sufficient rights using
 * the manageNotebookShares method.  The valid values that clients
 * should present to users for selection are given via the the
 * 'restrictions' field.</dd>
 * 
 * <dt>restrictions</dt>
 * <dd>The restrictions on which privileges may be individually
 * assigned to the recipient of this share relationship.</dd>
 * 
 * <dt>sharerUserId</dt>
 * <dd>The user id of the user who most recently shared the notebook
 * to this user. This field is currently unset for a MemberShareRelationship
 * created by joining a notebook that has been published to the business
 * (MemberShareRelationships where the individual privilege is unset).
 * This field is used by the service to convey information to the user, so
 * clients should treat it as read-only.
 * </dd>
 * </dl>
 */
declare class MemberShareRelationship {
  public displayName?: string;
  public recipientUserId?: number;
  public bestPrivilege?: ShareRelationshipPrivilegeLevel;
  public individualPrivilege?: ShareRelationshipPrivilegeLevel;
  public restrictions?: ShareRelationshipRestrictions;
  public sharerUserId?: number;

    constructor(args?: { displayName?: string; recipientUserId?: number; bestPrivilege?: ShareRelationshipPrivilegeLevel; individualPrivilege?: ShareRelationshipPrivilegeLevel; restrictions?: ShareRelationshipRestrictions; sharerUserId?: number; });
}

/**
 * Captures a collection of share relationships for a notebook, for
 * example, as returned by the getNotebookShares method.  The share
 * relationships fall into two broad categories: members, and
 * invitations that can be used to become members.
 * 
 * <dl>
 * <dt>invitations</dt>
 * <dd>A list of open invitations that can be redeemed into
 * memberships to the notebook.</dd>
 * 
 * <dt>memberships</dt>
 * <dd>A list of memberships of the notebook.  A member is identified
 * by their Evernote UserID and has rights to access the
 * notebook.</dd>
 * 
 * <dt>invitationRestrictions</dt>
 * <dd>The restrictions on what privileges may be granted to invitees
 * to this notebook. These restrictions may be specific to the calling
 * user or to the notebook itself. They represent the
 * union of all possible invite cases, so it is possible that once the
 * recipient of the invitation has been identified by the service, such
 * as by a business auto-join, the actual assigned privilege may change.
 * </dd>
 * </dl>
 */
declare class ShareRelationships {
  public invitations?: InvitationShareRelationship[];
  public memberships?: MemberShareRelationship[];
  public invitationRestrictions?: ShareRelationshipRestrictions;

    constructor(args?: { invitations?: InvitationShareRelationship[]; memberships?: MemberShareRelationship[]; invitationRestrictions?: ShareRelationshipRestrictions; });
}

/**
 * A structure that captures parameters used by clients to manage the
 * shares for a given notebook via the manageNotebookShares method.
 * 
 * <dl>
 * <dt>notebookGuid</dt>
 * <dd>The GUID of the notebook whose shares are being managed.</dd>
 * 
 * <dt>inviteMessage</dt>
 * <dd>If the service sends a message to invitees, this parameter will
 * be used to form the actual message that is sent.</dd>
 * 
 * <dt>membershipsToUpdate</dt>
 * <dd>The list of existing memberships to update.  This field is not
 * intended to be the full set of memberships for the notebook and
 * should only include those already-existing memberships that you
 * actually want to change.  If you want to remove shares, see the
 * unshares fields.  If you want to create a membership,
 * i.e. auto-join a business user, you can do this via the
 * invitationsToCreateOrUpdate field using an Evernote UserID of a
 * fellow business member (the created invitation is automatically
 * joined by the service, so the client is creating an
 * invitation, not a membership).</dd>
 * 
 * <dt>invitationsToCreateOrUpdate</dt>
 * <dd>The list of invitations to update, as matched by the identity
 * field of the InvitationShareRelationship instances, or to create if
 * an existing invitation does not exist.  This field is not intended
 * to be the full set of invitations on the notebook and should only
 * include those invitations that you wish to create or update.  Note
 * that your invitation could convert into a membership via a
 * service-supported auto-join operation.  This happens, for example,
 * when you use an invitation with an Evernote UserID type for a
 * recipient who is a member of the business to which the notebook
 * belongs.  Note that to discover the user IDs for business members,
 * the sharer must also be part of the business.</dd>
 * 
 * <dt>unshares</dt>
 * <dd>The list of share relationships to expunge from the service.
 * If the user identity is for an Evernote UserID, then matching invitations or
 * memberships will be removed. If it's an e-mail, then e-mail based shared notebook
 * invitations will be removed. If it's for an Identity ID, then any invitations that
 * match the identity (by identity ID or user ID or e-mail for legacy invitations) will be
 * removed.</dd>
 * </dl>
 */
declare class ManageNotebookSharesParameters {
  public notebookGuid?: string;
  public inviteMessage?: string;
  public membershipsToUpdate?: MemberShareRelationship[];
  public invitationsToCreateOrUpdate?: InvitationShareRelationship[];
  public unshares?: Types_ttypes.UserIdentity[];

    constructor(args?: { notebookGuid?: string; inviteMessage?: string; membershipsToUpdate?: MemberShareRelationship[]; invitationsToCreateOrUpdate?: InvitationShareRelationship[]; unshares?: Types_ttypes.UserIdentity[]; });
}

/**
 * A structure to capture certain errors that occurred during a call
 * to manageNotebookShares.  That method can be run best-effort,
 * meaning that some change requests can be applied while others fail.
 * Note that some errors such as system errors will still fail the
 * entire transaction regardless of running best effort.  When some
 * change requests do not succeed, the error conditions are captured
 * in instances of this class, captured by the identity of the share
 * relationship and one of the exception fields.
 * 
 * <dl>
 * <dt>userIdentity</dt>
 * <dd>The identity of the share relationship whose update encountered
 * an error.</dd>
 * 
 * <dt>userException</dt>
 * <dd>If the error is represented as an EDAMUserException that would
 * have otherwise been thrown without best-effort execution.  Only one
 * exception field will be set.</dd>
 * 
 * <dt>notFoundException</dt>
 * <dd>If the error is represented as an EDAMNotFoundException that would
 * have otherwise been thrown without best-effort execution.  Only one
 * exception field will be set.</dd>
 * </dl>
 */
declare class ManageNotebookSharesError {
  public userIdentity?: Types_ttypes.UserIdentity;
  public userException?: Errors_ttypes.EDAMUserException;
  public notFoundException?: Errors_ttypes.EDAMNotFoundException;

    constructor(args?: { userIdentity?: Types_ttypes.UserIdentity; userException?: Errors_ttypes.EDAMUserException; notFoundException?: Errors_ttypes.EDAMNotFoundException; });
}

/**
 * The return value of a call to the manageNotebookShares method.
 * 
 * <dl>
 * <dt>errors</dt>
 * <dd>If the method completed without throwing exceptions, some errors
 * might still have occurred, and in that case, this field will contain
 * the list of those errors the occurred.
 * </dd>
 * </dl>
 */
declare class ManageNotebookSharesResult {
  public errors?: ManageNotebookSharesError[];

    constructor(args?: { errors?: ManageNotebookSharesError[]; });
}

/**
 * A structure used to share a note with one or more recipients at a given privilege.
 * 
 * <dl>
 *   <dt>noteGuid</dt>
 *   <dd>The GUID of the note.</dd>
 * 
 *   <dt>recipientThreadId</dt>
 *   <dd>The recipients of the note share specified as a messaging thread ID. If you
 *       have an existing messaging thread to share the note with, specify its ID
 *       here instead of recipientContacts in order to properly support defunct
 *       identities. The sharer must be a participant of the thread. Either this
 *       field or recipientContacts must be set.</dd>
 * 
 *   <dt>recipientContacts</dt>
 *   <dd>The recipients of the note share specified as a list of contacts. This should
 *       only be set if the sharing takes place before the thread is created. Use
 *       recipientThreadId instead when sharing with an existing thread. Either this
 *       field or recipientThreadId must be set.</dd>
 * 
 *   <dt>privilege</dt>
 *   <dd>The privilege level to be granted.</dd>
 * </dl>
 */
declare class SharedNoteTemplate {
  public noteGuid?: string;
  public recipientThreadId?: Int64;
  public recipientContacts?: Types_ttypes.Contact[];
  public privilege?: Types_ttypes.SharedNotePrivilegeLevel;

    constructor(args?: { noteGuid?: string; recipientThreadId?: Int64; recipientContacts?: Types_ttypes.Contact[]; privilege?: Types_ttypes.SharedNotePrivilegeLevel; });
}

/**
 * A structure used to share a notebook with one or more recipients at a given privilege.
 * 
 * <dl>
 *   <dt>notebookGuid</dt>
 *   <dd>The GUID of the notebook.</dd>
 * 
 *   <dt>recipientThreadId</dt>
 *   <dd>The recipients of the notebook share specified as a messaging thread ID. If you
 *       have an existing messaging thread to share the note with, specify its ID
 *       here instead of recipientContacts in order to properly support defunct
 *       identities. The sharer must be a participant of the thread. Either this field
 *       or recipientContacts must be set.</dd>
 * 
 *   <dt>recipientContacts</dt>
 *   <dd>The recipients of the notebook share specified as a list of contacts. This should
 *       only be set if the sharing takes place before the thread is created. Use
 *       recipientThreadId instead when sharing with an existing thread. Either this
 *       field or recipientThreadId must be set.</dd>
 * 
 *   <dt>privilege</dt>
 *   <dd>The privilege level to be granted.</dd>
 * </dl>
 */
declare class NotebookShareTemplate {
  public notebookGuid?: string;
  public recipientThreadId?: Int64;
  public recipientContacts?: Types_ttypes.Contact[];
  public privilege?: Types_ttypes.SharedNotebookPrivilegeLevel;

    constructor(args?: { notebookGuid?: string; recipientThreadId?: Int64; recipientContacts?: Types_ttypes.Contact[]; privilege?: Types_ttypes.SharedNotebookPrivilegeLevel; });
}

/**
 * A structure containing the results of a call to createOrUpdateNotebookShares.
 * 
 * <dl>
 *   <dt>updateSequenceNum</dt>
 *   <dd>The USN of the notebook after the call.</dd>
 * 
 *   <dt>matchingShares</dt>
 *   <dd>A list of SharedNotebook records that match the desired recipients. These
 *       records may have been either created or updated by the call to
 *       createOrUpdateNotebookShares, or they may have been at the desired privilege
 *       privilege level prior to the call.</dd>
 * </dl>
 */
declare class CreateOrUpdateNotebookSharesResult {
  public updateSequenceNum?: number;
  public matchingShares?: Types_ttypes.SharedNotebook[];

    constructor(args?: { updateSequenceNum?: number; matchingShares?: Types_ttypes.SharedNotebook[]; });
}

/**
 * This structure is used by the service to communicate to clients, via
 * getNoteShareRelationships, which privilege levels are assignable to the
 * target of a note share relationship.
 * 
 * <dl>
 * <dt>noSetReadNote</dt>
 * <dd>This value is true if the user is not allowed to set the privilege
 * level to SharedNotePrivilegeLevel.READ_NOTE.</dd>
 * 
 * <dt>noSetModifyNote</dt>
 * <dd>This value is true if the user is not allowed to set the privilege
 * level to SharedNotePrivilegeLevel.MODIFY_NOTE.</dd>
 * 
 * <dt>noSetFullAccess</dt>
 * <dd>This value is true if the user is not allowed to set the
 * privilege level to SharedNotePrivilegeLevel.FULL_ACCESS.</dd>
 * </dl>
 */
declare class NoteShareRelationshipRestrictions {
  public noSetReadNote?: boolean;
  public noSetModifyNote?: boolean;
  public noSetFullAccess?: boolean;

    constructor(args?: { noSetReadNote?: boolean; noSetModifyNote?: boolean; noSetFullAccess?: boolean; });
}

/**
 * Describes the association between a Note and an Evernote User who is
 * a member of that note.
 * 
 * <dl>
 * <dt>displayName</dt>
 * <dd>The string that clients should show to users to represent this
 * member.</dd>
 * 
 * <dt>recipientUserId</dt>
 * <dd>The Evernote UserID of the user who is a member to the note.</dd>
 * 
 * <dt>privilege</dt>
 * <dd>The privilege at which the member can access the note,
 * which is the best privilege granted to the user across all of their
 * individual shares for this note. This field is used by the service
 * to convey information to the user, so clients should treat it as
 * read-only.</dd>
 * 
 * <dt>restrictions</dt>
 * <dd>The restrictions on which privileges may be individually
 * assigned to the recipient of this share relationship. This field
 * is used by the service to convey information to the user, so
 * clients should treat it as read-only.</dd>
 * 
 * <dt>sharerUserId</dt>
 * <dd>The user id of the user who most recently shared the note with
 * this user. This field is used by the service to convey information
 * to the user, so clients should treat it as read-only.</dd>
 * </dl>
 */
declare class NoteMemberShareRelationship {
  public displayName?: string;
  public recipientUserId?: number;
  public privilege?: Types_ttypes.SharedNotePrivilegeLevel;
  public restrictions?: NoteShareRelationshipRestrictions;
  public sharerUserId?: number;

    constructor(args?: { displayName?: string; recipientUserId?: number; privilege?: Types_ttypes.SharedNotePrivilegeLevel; restrictions?: NoteShareRelationshipRestrictions; sharerUserId?: number; });
}

/**
 * Describes an invitation to a person to use their Evernote credentials
 * to gain access to a note belonging to another user.
 * 
 * <dl>
 * <dt>displayName</dt>
 * <dd>The string that clients should show to users to represent this
 * invitation.</dd>
 * 
 * <dt>recipientIdentityId</dt>
 * <dd>Identifies the identity of the invitation recipient. Once the
 * identity has been claimed by an Evernote user and they have accessed
 * the note at least once, the invitation will be used up and will no
 * longer be returned by the service to clients. Instead, that recipient
 * will be included in the list of NoteMemberShareRelationships.</dd>
 * 
 * <dt>privilege</dt>
 * <dd>The privilege level that the recipient will be granted when they
 * accept this invitation. If the user already has a higher privilege to
 * access this note then this will not affect the recipient's privileges.</dd>
 * 
 * <dt>sharerUserId</dt>
 * <dd>The user id of the user who most recently shared this note to this
 * recipient. This field is used by the service to convey information
 * to the user, so clients should treat it as read-only.</dd>
 */
declare class NoteInvitationShareRelationship {
  public displayName?: string;
  public recipientIdentityId?: Int64;
  public privilege?: Types_ttypes.SharedNotePrivilegeLevel;
  public sharerUserId?: number;

    constructor(args?: { displayName?: string; recipientIdentityId?: Int64; privilege?: Types_ttypes.SharedNotePrivilegeLevel; sharerUserId?: number; });
}

/**
 * Captures a collection of share relationships for a single note,
 * for example, as returned by the getNoteShares method. The share
 * relationships fall into two broad categories: members, and
 * invitations that can be used to become members.
 * 
 * <dl>
 * <dt>invitations</dt>
 * <dd>A list of open invitations that can be redeemed into
 * memberships to the note.</dd>
 * 
 * <dt>memberships</dt>
 * <dd>A list of memberships of the noteb. A member is identified
 * by their Evernote UserID and has rights to access the
 * note.</dd>
 * 
 * <dt>restrictions</dt>
 * <dd>The restrictions on which privileges may be assigned to the recipient
 * of an open invitation. These restrictions only apply to invitations;
 * restrictions on memberships are specified on the NoteMemberShareRelationship.
 * This field is used by the service to convey information to the user, so
 * clients should treat it as read-only.</dd>
 * 
 * </dl>
 */
declare class NoteShareRelationships {
  public invitations?: NoteInvitationShareRelationship[];
  public memberships?: NoteMemberShareRelationship[];
  public invitationRestrictions?: NoteShareRelationshipRestrictions;

    constructor(args?: { invitations?: NoteInvitationShareRelationship[]; memberships?: NoteMemberShareRelationship[]; invitationRestrictions?: NoteShareRelationshipRestrictions; });
}

/**
 * Captures parameters used by clients to manage the shares for a given
 * note via the manageNoteShares function. This is used only to manage
 * the existing memberships and invitations for a note. To invite a new
 * recipient, use NoteStore.createOrUpdateSharedNotes.
 * 
 * The only field of an existing membership or invitation that can be
 * updated by this function is the share privilege.
 * 
 * <dl>
 *   <dt>noteGuid</dt>
 *   <dd>The GUID of the note whose shares are being managed.</dd>
 * 
 *   <dt>membershipsToUpdate</dt>
 *   <dd>A list of existing memberships to update. This field is not
 *     meant to be the full set of memberships for the note. Clients
 *     should only include those existing memberships that they wish
 *     to modify. To remove an existing membership, see the unshares
 *     field.</dd>
 * 
 *   <dt>invitationsToUpdate</dt>
 *   <dd>The list of outstanding invitations to update, as matched by the
 *     identity field of the NoteInvitationShareRelatioship instances.
 *     This field is not meant to be the full set of invitations for the
 *     note. Clients should only include those existing invitations that
 *     they wish to modify.</dd>
 * 
 *   <dt>membershipsToUnshare</dt>
 *   <dd>A list of existing memberships to expunge from the service.</dd>
 * 
 *   <dt>invitationsToUnshare</dt>
 *   <dd>A list of outstanding invitations to expunge from the service.</dd>
 * </dl>
 */
declare class ManageNoteSharesParameters {
  public noteGuid?: string;
  public membershipsToUpdate?: NoteMemberShareRelationship[];
  public invitationsToUpdate?: NoteInvitationShareRelationship[];
  public membershipsToUnshare?: number[];
  public invitationsToUnshare?: Int64[];

    constructor(args?: { noteGuid?: string; membershipsToUpdate?: NoteMemberShareRelationship[]; invitationsToUpdate?: NoteInvitationShareRelationship[]; membershipsToUnshare?: number[]; invitationsToUnshare?: Int64[]; });
}

/**
 * Captures errors that occur during a call to manageNoteShares. That
 * function can be run best-effort, meaning that some change requests can
 * be applied while others fail. Note that some errors such as system
 * exceptions may still cause the entire call to fail.
 * 
 * Only one of the two ID fields will be set on a given error.
 * 
 * Only one of the two exception fields will be set on a given error.
 * 
 * <dl>
 *   <dt>identityID</dt>
 *   <dd>The identity ID of an outstanding invitation that was not updated
 *     due to the error.</dd>
 * 
 *   <dt>userID</dt>
 *   <dd>The user ID of an existing membership that was not updated due
 *     to the error.</dd>
 * 
 *   <dt>userException</dt>
 *   <dd>If the error is represented as an EDAMUserException that would
 *     have otherwise been thrown without best-effort execution.</dd>
 * 
 *   <dt>notFoundException</dt>
 *   <dd>If the error is represented as an EDAMNotFoundException that
 *     would have otherwise been thrown without best-effort execution.
 *     The identifier field of the exception will be either "Identity.id"
 *     or "User.id", indicating that no existing share could be found for
 *     the specified recipient.</dd>
 * </dl>
 */
declare class ManageNoteSharesError {
  public identityID?: Int64;
  public userID?: number;
  public userException?: Errors_ttypes.EDAMUserException;
  public notFoundException?: Errors_ttypes.EDAMNotFoundException;

    constructor(args?: { identityID?: Int64; userID?: number; userException?: Errors_ttypes.EDAMUserException; notFoundException?: Errors_ttypes.EDAMNotFoundException; });
}

/**
 * The return value of a call to the manageNoteShares function.
 * 
 * <dl>
 *   <dt>errors</dt>
 *   <dd>If the call succeeded without throwing an exception, some errors
 *     might still have occurred. In that case, this field will contain the
 *     list of errors.</dd>
 * </dl>
 */
declare class ManageNoteSharesResult {
  public errors?: ManageNoteSharesError[];

    constructor(args?: { errors?: ManageNoteSharesError[]; });
}
