//
// Autogenerated by Thrift Compiler (0.22.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import thrift = require('thrift');
import Thrift = thrift.Thrift;
import Q = thrift.Q;
import Int64 = require('node-int64');
import Types_ttypes = require('./Types_types.js');
import Errors_ttypes = require('./Errors_types.js');



/**
 *  This structure is used to provide publicly-available user information
 *  about a particular account.
 * <dl>
 *  <dt>userId:</dt>
 *    <dd>
 *    The unique numeric user identifier for the user account.
 *    </dd>
 *  <dt>serviceLevel:</dt>
 *    <dd>
 *    The service level of the account.
 *    </dd>
 *  <dt>noteStoreUrl:</dt>
 *    <dd>
 *    This field will contain the full URL that clients should use to make
 *    NoteStore requests to the server shard that contains that user's data.
 *    I.e. this is the URL that should be used to create the Thrift HTTP client
 *    transport to send messages to the NoteStore service for the account.
 *    </dd>
 *  <dt>webApiUrlPrefix:</dt>
 *    <dd>
 *    This field will contain the initial part of the URLs that should be used
 *    to make requests to Evernote's thin client "web API", which provide
 *    optimized operations for clients that aren't capable of manipulating
 *    the full contents of accounts via the full Thrift data model. Clients
 *    should concatenate the relative path for the various servlets onto the
 *    end of this string to construct the full URL, as documented on our
 *    developer web site.
 *    </dd>
 *  </dl>
 */
declare class PublicUserInfo {
  public userId: number;
  public serviceLevel?: Types_ttypes.ServiceLevel;
  public username?: string;
  public noteStoreUrl?: string;
  public webApiUrlPrefix?: string;

    constructor(args?: { userId: number; serviceLevel?: Types_ttypes.ServiceLevel; username?: string; noteStoreUrl?: string; webApiUrlPrefix?: string; });
}

/**
 * <dl>
 * <dt>noteStoreUrl:</dt>
 *   <dd>
 *   This field will contain the full URL that clients should use to make
 *   NoteStore requests to the server shard that contains that user's data.
 *   I.e. this is the URL that should be used to create the Thrift HTTP client
 *   transport to send messages to the NoteStore service for the account.
 *   </dd>
 * <dt>webApiUrlPrefix:</dt>
 *   <dd>
 *   This field will contain the initial part of the URLs that should be used
 *   to make requests to Evernote's thin client "web API", which provide
 *   optimized operations for clients that aren't capable of manipulating
 *   the full contents of accounts via the full Thrift data model. Clients
 *   should concatenate the relative path for the various servlets onto the
 *   end of this string to construct the full URL, as documented on our
 *   developer web site.
 *   </dd>
 * <dt>userStoreUrl:</dt>
 *   <dd>
 *   This field will contain the full URL that clients should use to make UserStore
 *   requests after successfully authenticating. I.e. this is the URL that should be used
 *   to create the Thrift HTTP client transport to send messages to the UserStore service
 *   for this account.
 *   </dd>
 * <dt>utilityUrl:</dt>
 *   <dd>
 *   This field will contain the full URL that clients should use to make Utility requests
 *   to the server shard that contains that user's data. I.e. this is the URL that should
 *   be used to create the Thrift HTTP client transport to send messages to the Utility
 *   service for the account.
 *   </dd>
 * <dt>messageStoreUrl:</dt>
 *   <dd>
 *   This field will contain the full URL that clients should use to make MessageStore
 *   requests to the server. I.e. this is the URL that should be used to create the
 *   Thrift HTTP client transport to send messages to the MessageStore service for the
 *   account.
 *   </dd>
 * <dt>userWebSocketUrl:</dt>
 *   <dd>
 *   This field will contain the full URL that clients should use when opening a
 *   persistent web socket to recieve notification of events for the authenticated user.
 *   </dd>
 * </dl>
 */
declare class UserUrls {
  public noteStoreUrl?: string;
  public webApiUrlPrefix?: string;
  public userStoreUrl?: string;
  public utilityUrl?: string;
  public messageStoreUrl?: string;
  public userWebSocketUrl?: string;

    constructor(args?: { noteStoreUrl?: string; webApiUrlPrefix?: string; userStoreUrl?: string; utilityUrl?: string; messageStoreUrl?: string; userWebSocketUrl?: string; });
}

/**
 *  When an authentication (or re-authentication) is performed, this structure
 *  provides the result to the client.
 * <dl>
 *  <dt>currentTime:</dt>
 *    <dd>
 *    The server-side date and time when this result was
 *    generated.
 *    </dd>
 *  <dt>authenticationToken:</dt>
 *    <dd>
 *    Holds an opaque, ASCII-encoded token that can be
 *    used by the client to perform actions on a NoteStore.
 *    </dd>
 *  <dt>expiration:</dt>
 *    <dd>
 *    Holds the server-side date and time when the
 *    authentication token will expire.
 *    This time can be compared to "currentTime" to produce an expiration
 *    time that can be reconciled with the client's local clock.
 *    </dd>
 *  <dt>user:</dt>
 *    <dd>
 *    Holds the information about the account which was
 *    authenticated if this was a full authentication.  May be absent if this
 *    particular authentication did not require user information.
 *    </dd>
 *  <dt>publicUserInfo:</dt>
 *    <dd>
 *    If this authentication result was achieved without full permissions to
 *    access the full User structure, this field may be set to give back
 *    a more limited public set of data.
 *    </dd>
 *  <dt>noteStoreUrl:</dt>
 *    <dd>
 *    DEPRECATED - Client applications should use urls.noteStoreUrl.
 *    </dd>
 *  <dt>webApiUrlPrefix:</dt>
 *    <dd>
 *    DEPRECATED - Client applications should use urls.webApiUrlPrefix.
 *    </dd>
 *  <dt>secondFactorRequired:</dt>
 *    <dd>
 *    If set to true, this field indicates that the user has enabled two-factor
 *    authentication and must enter their second factor in order to complete
 *    authentication. In this case the value of authenticationResult will be
 *    a short-lived authentication token that may only be used to make a
 *    subsequent call to completeTwoFactorAuthentication.
 *    </dd>
 *  <dt>secondFactorDeliveryHint:</dt>
 *    <dd>
 *    When secondFactorRequired is set to true, this field may contain a string
 *    describing the second factor delivery method that the user has configured.
 *    This will typically be an obfuscated mobile device number, such as
 *    "(xxx) xxx-x095". This string can be displayed to the user to remind them
 *    how to obtain the required second factor.
 *    </dd>
 *  <dt>urls</dt>
 *    <dd>
 *    This structure will contain all of the URLs that clients need to make requests to the
 *    Evernote service on behalf of the authenticated User.
 *    </dd>
 *  </dl>
 */
declare class AuthenticationResult {
  public currentTime: Int64;
  public authenticationToken: string;
  public expiration: Int64;
  public user?: Types_ttypes.User;
  public publicUserInfo?: PublicUserInfo;
  public noteStoreUrl?: string;
  public webApiUrlPrefix?: string;
  public secondFactorRequired?: boolean;
  public secondFactorDeliveryHint?: string;
  public urls?: UserUrls;

    constructor(args?: { currentTime: Int64; authenticationToken: string; expiration: Int64; user?: Types_ttypes.User; publicUserInfo?: PublicUserInfo; noteStoreUrl?: string; webApiUrlPrefix?: string; secondFactorRequired?: boolean; secondFactorDeliveryHint?: string; urls?: UserUrls; });
}

/**
 *  This structure describes a collection of bootstrap settings.
 * <dl>
 *  <dt>serviceHost:</dt>
 *    <dd>
 *    The hostname and optional port for composing Evernote web service URLs.
 *    This URL can be used to access the UserStore and related services,
 *    but must not be used to compose the NoteStore URL. Client applications
 *    must handle serviceHost values that include only the hostname
 *    (e.g. www.evernote.com) or both the hostname and port (e.g. www.evernote.com:8080).
 *    If no port is specified, or if port 443 is specified, client applications must
 *    use the scheme "https" when composing URLs. Otherwise, a client must use the
 *    scheme "http".
 *  </dd>
 *  <dt>marketingUrl:</dt>
 *    <dd>
 *    The URL stem for the Evernote corporate marketing website, e.g. http://www.evernote.com.
 *    This stem can be used to compose website URLs. For example, the URL of the Evernote
 *    Trunk is composed by appending "/about/trunk/" to the value of marketingUrl.
 *    </dd>
 *  <dt>supportUrl:</dt>
 *    <dd>
 *    The full URL for the Evernote customer support website, e.g. https://support.evernote.com.
 *    </dd>
 *  <dt>accountEmailDomain:</dt>
 *    <dd>
 *    The domain used for an Evernote user's incoming email address, which allows notes to
 *    be emailed into an account. E.g. m.evernote.com.
 *    </dd>
 *  <dt>enableFacebookSharing:</dt>
 *    <dd>
 *    Whether the client application should enable sharing of notes on Facebook.
 *    </dd>
 *  <dt>enableGiftSubscriptions:</dt>
 *    <dd>
 *    Whether the client application should enable gift subscriptions.
 *    </dd>
 *  <dt>enableSupportTickets:</dt>
 *    <dd>
 *    Whether the client application should enable in-client creation of support tickets.
 *    </dd>
 *  <dt>enableSharedNotebooks:</dt>
 *    <dd>
 *    Whether the client application should enable shared notebooks.
 *    </dd>
 *  <dt>enableSingleNoteSharing:</dt>
 *    <dd>
 *    Whether the client application should enable single note sharing.
 *    </dd>
 *  <dt>enableSponsoredAccounts:</dt>
 *    <dd>
 *    Whether the client application should enable sponsored accounts.
 *    </dd>
 *  <dt>enableTwitterSharing:</dt>
 *    <dd>
 *    Whether the client application should enable sharing of notes on Twitter.
 *    </dd>
 *  <dt>enableGoogle:</dt>
 *    <dd>
 *    Whether the client application should enable authentication with Google,
 *    for example to allow integration with a user's Gmail contacts.
 *  </dl>
 */
declare class BootstrapSettings {
  public serviceHost: string;
  public marketingUrl: string;
  public supportUrl: string;
  public accountEmailDomain: string;
  public enableFacebookSharing?: boolean;
  public enableGiftSubscriptions?: boolean;
  public enableSupportTickets?: boolean;
  public enableSharedNotebooks?: boolean;
  public enableSingleNoteSharing?: boolean;
  public enableSponsoredAccounts?: boolean;
  public enableTwitterSharing?: boolean;
  public enableLinkedInSharing?: boolean;
  public enablePublicNotebooks?: boolean;
  public enableGoogle?: boolean;

    constructor(args?: { serviceHost: string; marketingUrl: string; supportUrl: string; accountEmailDomain: string; enableFacebookSharing?: boolean; enableGiftSubscriptions?: boolean; enableSupportTickets?: boolean; enableSharedNotebooks?: boolean; enableSingleNoteSharing?: boolean; enableSponsoredAccounts?: boolean; enableTwitterSharing?: boolean; enableLinkedInSharing?: boolean; enablePublicNotebooks?: boolean; enableGoogle?: boolean; });
}

/**
 *  This structure describes a collection of bootstrap settings.
 * <dl>
 *  <dt>name:</dt>
 *    <dd>
 *    The unique name of the profile, which is guaranteed to remain consistent across
 *    calls to getBootstrapInfo.
 *    </dd>
 *  <dt>settings:</dt>
 *    <dd>
 *    The settings for this profile.
 *    </dd>
 *  </dl>
 */
declare class BootstrapProfile {
  public name: string;
  public settings: BootstrapSettings;

    constructor(args?: { name: string; settings: BootstrapSettings; });
}

/**
 *  This structure describes a collection of bootstrap profiles.
 * <dl>
 *  <dt>profiles:</dt>
 *    <dd>
 *    List of one or more bootstrap profiles, in descending
 *    preference order.
 *    </dd>
 *  </dl>
 */
declare class BootstrapInfo {
  public profiles: BootstrapProfile[];

    constructor(args?: { profiles: BootstrapProfile[]; });
}

/**
 * The major version number for the current revision of the EDAM protocol.
 * Clients pass this to the service using UserStore.checkVersion at the
 * beginning of a session to confirm that they are not out of date.
 */
declare var EDAM_VERSION_MAJOR: number;

/**
 * The minor version number for the current revision of the EDAM protocol.
 * Clients pass this to the service using UserStore.checkVersion at the
 * beginning of a session to confirm that they are not out of date.
 */
declare var EDAM_VERSION_MINOR: number;
