name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: ./.github/actions/setup-bun-env
      - run: bunx biome format .
      - run: bunx biome lint .
      - run: bunx tsc --noEmit -p tsconfig.check.json

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: ./.github/actions/setup-bun-env
      - run: bun test tests/unit

  build:
    needs: [lint-and-typecheck, unit-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: ./.github/actions/setup-bun-env
      - run: bunx tsc
      - uses: actions/upload-artifact@v7.0.0
        with:
          name: build
          path: build/

  integration-tests:
    needs: [lint-and-typecheck, unit-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: ./.github/actions/setup-bun-env
      - run: bun test tests/integration
